/**
 * 슬랙 실시간 알림 유틸리티
 */

const SYSTEM_SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL;

/**
 * 슬랙으로 메시지를 전송합니다.
 * @param payload 슬랙 API 페이로드 (text 또는 blocks)
 * @param customWebhookUrl 보고서별로 설정된 개별 웹후크 URL (선택 사항)
 */
async function sendSlackMessage(payload: any, customWebhookUrl?: string | null) {
    // 1순위: 보고서별 개별 설정된 웹후크 URL
    // 2순위: 시스템 글로벌 공통 웹후크 URL
    const targetUrl = customWebhookUrl || SYSTEM_SLACK_WEBHOOK_URL;

    if (!targetUrl) {
        console.warn('사용 가능한 슬랙 웹후크 URL이 없어 알림을 건너뜁니다.');
        return;
    }

    try {
        console.log(`슬랙 알림 전송 시도중 (${customWebhookUrl ? '전용 채널' : '공통 채널'})...`, payload.text);
        const response = await fetch(targetUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload),
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error('슬랙 메시지 전송 실패:', errorText);
        } else {
            console.log('슬랙 알림 전송 성공!');
        }
    } catch (err) {
        console.error('슬랙 알림 오류:', err);
    }
}

/**
 * 신규 데이터 단건 등록 알림
 */
export async function notifyNewDataRow(
    reportName: string, 
    userName: string, 
    rowData: any, 
    columns: any[],
    customWebhookUrl?: string | null
) {
    // 첫 번째 컬럼 정보 추출 (보안상 의미 있는 식별자로 활용)
    const firstCol = columns.find(c => !c.isAutoGenerated) || columns[0];
    const firstVal = firstCol ? rowData[firstCol.name] : 'N/A';
    
    // 데이터ID 추출 (있을 경우)
    const dataId = rowData['데이터ID'] || 'N/A';

    const blocks = [
        {
            type: 'header',
            text: {
                type: 'plain_text',
                text: '📢 신규 데이터 등록 알림',
                emoji: true
            }
        },
        {
            type: 'section',
            fields: [
                {
                    type: 'mrkdwn',
                    text: `*보고서:* ${reportName}`
                },
                {
                    type: 'mrkdwn',
                    text: `*등록자:* ${userName}`
                }
            ]
        },
        {
            type: 'section',
            text: {
                type: 'mrkdwn',
                text: `*주요 내용:* [${firstCol?.name || '항목'}] ${firstVal}\n*데이터 ID:* ${dataId}`
            }
        },
        {
            type: 'context',
            elements: [
                {
                    type: 'mrkdwn',
                    text: `🕒 등록 시간: ${new Date().toLocaleString('ko-KR')}`
                }
            ]
        }
    ];

    await sendSlackMessage({
        text: `[${reportName}] 신규 데이터 등록: ${firstVal}`,
        blocks
    }, customWebhookUrl);
}

/**
 * 엑셀 일괄 업로드 완료 알림
 */
export async function notifyBulkUpload(
    reportName: string, 
    userName: string, 
    count: number, 
    representativeRow?: any, 
    columns?: any[],
    customWebhookUrl?: string | null
) {
    const blocks: any[] = [
        {
            type: 'header',
            text: {
                type: 'plain_text',
                text: '📊 엑셀 일괄 업로드 완료',
                emoji: true
            }
        },
        {
            type: 'section',
            fields: [
                {
                    type: 'mrkdwn',
                    text: `*보고서:* ${reportName}`
                },
                {
                    type: 'mrkdwn',
                    text: `*등록자:* ${userName}`
                }
            ]
        },
        {
            type: 'section',
            text: {
                type: 'mrkdwn',
                text: `*업로드 건수:* 총 \`${count}\`건이 성공적으로 등록되었습니다.`
            }
        }
    ];

    // 첫 번째 행의 샘플 정보 추가 (있을 경우)
    if (representativeRow && columns) {
        const firstCol = columns.find(c => !c.isAutoGenerated) || columns[0];
        const firstVal = firstCol ? representativeRow[firstCol.name] : 'N/A';
        
        blocks.push({
            type: 'section',
            text: {
                type: 'mrkdwn',
                text: `*대표 데이터 샘플:* [${firstCol?.name || '항목'}] ${firstVal}`
            }
        });
    }

    blocks.push({
        type: 'context',
        elements: [
            {
                type: 'mrkdwn',
                text: `🕒 완료 시간: ${new Date().toLocaleString('ko-KR')}`
            }
        ]
    });

    await sendSlackMessage({
        text: `[${reportName}] 엑셀 일괄 업로드 완료 (${count}건)`,
        blocks
    }, customWebhookUrl);
}

/** 워크스페이스 항목 오버레이 링크 — userId+link 기준 알림 통합 키로 사용 */
export function workspaceOpenItemLink(itemId: string): string {
    return `/workspace?openItem=${encodeURIComponent(itemId)}`;
}

/**
 * 동일 userId + link 인앱 알림을 한 건만 유지합니다(UPSERT).
 * 워크스페이스 한 작업에 알림이 여러 번 쌓이는 것을 방지합니다.
 */
export async function upsertInAppNotificationByLink(data: {
    userId: string;
    link: string;
    title: string;
    message?: string;
    type?: 'INFO' | 'WARNING' | 'ALERT';
}) {
    // [개선] 더 이상 기존 알림을 덮어쓰지 않고, 새로운 이력으로 추가(Insert)합니다.
    // 프론트엔드에서 link 기준으로 그룹화하여 보여주므로 시각적 통합은 유지됩니다.
    await createInAppNotification(data);
    console.log(`[Notification] History point added for user=${data.userId}, title=${data.title}`);
}

/**
 * 인앱 알림을 생성하여 DB에 저장합니다.
 */
export async function createInAppNotification(data: {
    userId: string;
    title: string;
    message?: string;
    link?: string;
    type?: 'INFO' | 'WARNING' | 'ALERT';
}) {
    const { insertRows } = await import('@/egdesk-helpers');


    try {
        await insertRows('notification', [{
            
            userId: String(data.userId),
            title: data.title,
            message: data.message || null,
            link: data.link || null,
            type: data.type || 'INFO',
            isRead: '0',
            createdAt: new Date().toISOString()
        }]);
        console.log(`[Notification] In-app alert created for user: ${data.userId}`);
    } catch (err) {
        console.error('[Notification] Failed to create in-app alert:', err);
    }
}

/**
 * 시스템 활동 로그를 생성합니다. (기안자/수행자 전용)
 */
export async function logActivity(data: {
    userId: string;
    title: string;
    message?: string;
    link?: string;
    type?: 'ACTIVITY';
}) {
    const { insertRows } = await import('@/egdesk-helpers');


    try {
        await insertRows('notification', [{
            
            userId: data.userId,
            title: data.title,
            message: data.message || null,
            link: data.link || null,
            type: data.type || 'ACTIVITY',
            isRead: '1', // 활동 로그는 기안자가 이미 한 일이므로 기본 읽음 처리
            createdAt: new Date().toISOString()
        }]);
    } catch (err) {
        console.error('[Notification] Failed to log activity:', err);
    }
}

/**
 * ADMIN 역할을 가진 모든 사용자에게 인앱 알림을 발송합니다.
 * 관리자 조회 실패 시 silent skip — 주 처리 흐름을 막지 않습니다.
 */
export async function notifyAdmins(data: {
    title: string;
    message: string;
    type: 'INFO' | 'WARNING' | 'ALERT';
    link: string;
}) {
    try {
        const { queryTable } = await import('@/egdesk-helpers');
        const admins = await queryTable('user', { filters: { role: 'ADMIN' } });
        const adminList = Array.isArray(admins) ? admins : (admins?.rows || []);

        if (!adminList || adminList.length === 0) {
            console.warn('[notifyAdmins] 관리자 계정이 없어 알림을 건너뜁니다.');
            return;
        }

        await Promise.all(
            adminList.map((admin: any) =>
                createInAppNotification({
                    userId: String(admin.id),
                    title: data.title,
                    message: data.message,
                    type: data.type,
                    link: data.link,
                })
            )
        );

        console.log(`[notifyAdmins] ${adminList.length}명의 관리자에게 알림 발송 완료.`);
    } catch (err) {
        // 관리자 알림은 부가 기능 — 실패해도 주 흐름을 중단하지 않음
        console.error('[notifyAdmins] 관리자 알림 발송 실패 (silent skip):', err);
    }
}

/**
 * 관리자 전원에게 동일 링크 알림을 UPSERT (제외 userId는 생략 — 업로더 전용 알림과 중복 방지)
 */
export async function notifyAdminsUpsert(data: {
    title: string;
    message: string;
    type: 'INFO' | 'WARNING' | 'ALERT';
    link: string;
    excludeUserIds?: string[];
}) {
    try {
        const { queryTable } = await import('@/egdesk-helpers');
        const admins = await queryTable('user', { filters: { role: 'ADMIN' } });
        const adminList = Array.isArray(admins) ? admins : (admins?.rows || []);
        const exclude = new Set((data.excludeUserIds || []).map(String));

        if (!adminList || adminList.length === 0) {
            console.warn('[notifyAdminsUpsert] 관리자 계정이 없어 건너뜁니다.');
            return;
        }

        await Promise.all(
            adminList
                .filter((a: any) => !exclude.has(String(a.id)))
                .map((admin: any) =>
                    upsertInAppNotificationByLink({
                        userId: String(admin.id),
                        link: data.link,
                        title: data.title,
                        message: data.message,
                        type: data.type
                    })
                )
        );

        console.log(`[notifyAdminsUpsert] 완료 (제외 ${exclude.size}명)`);
    } catch (err) {
        console.error('[notifyAdminsUpsert] 실패 (silent skip):', err);
    }
}
