
const fetch = require('node-fetch');
require('dotenv').config({ path: '.env.local' });

const EGDESK_CONFIG = {
  apiUrl: process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080',
  apiKey: process.env.NEXT_PUBLIC_EGDESK_API_KEY || 'a87d1623-34c1-43fe-87c8-9fa8263d71a4',
};

async function callUserDataTool(toolName, args = {}) {
  const body = JSON.stringify({ tool: toolName, arguments: args });
  const headers = {
    'Content-Type': 'application/json',
    'X-Api-Key': EGDESK_CONFIG.apiKey
  };

  const response = await fetch(`${EGDESK_CONFIG.apiUrl}/user-data/tools/call`, {
    method: 'POST',
    headers,
    body
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  const resultBody = await response.json();
  if (!resultBody.success) {
    throw new Error(resultBody.error || 'Tool call failed');
  }

  // Parse MCP response format
  const content = resultBody.result?.content?.[0]?.text;
  if (!content) return null;
  
  try {
     return JSON.parse(content);
  } catch(e) {
     return content;
  }
}

async function checkSheet1() {
  try {
    console.log('--- 1. Listing all reports in "report" table ---');
    const reports = await callUserDataTool('user_data_query', {
      tableName: 'report',
      orderBy: 'id',
      orderDirection: 'DESC',
      limit: 10
    });

    const reportRows = reports?.rows || reports || [];
    if (!reportRows || reportRows.length === 0) {
      console.log('No reports found in "report" table.');
      return;
    }

    console.log('\n--- All Reports ---');
    reportRows.forEach(r => {
      console.log(`ID: ${r.id} | Name: ${r.name} | Deleted: ${r.isDeleted} | Table: ${r.tableName}`);
    });

    // Pick the most recent non-deleted report or the one named Sheet1
    const activeReports = reportRows.filter(r => !r.isDeleted || r.isDeleted === 0 || r.isDeleted === '0');
    const report = activeReports.find(r => r.name.toLowerCase().includes('sheet1')) || activeReports[0] || reportRows[0];
    
    if (!report) {
      console.log('\nNo active reports found.');
      return;
    }

    const physicalTableName = report.tableName;
    console.log(`\n--- 2. Checking physical schema for: ${physicalTableName} ---`);
    const schema = await callUserDataTool('user_data_get_schema', { tableName: physicalTableName });
    
    console.log('Physical Schema:');
    console.log(JSON.stringify(schema, null, 2));

    console.log('\n--- 3. Analysis ---');
    const columns = JSON.parse(report.columns);
    const idCol = columns.find(c => c.isAutoGenerated);
    
    if (idCol) {
      console.log(`Metadata: Found AutoGenerated column: "${idCol.name}" (Type: ${idCol.type})`);
    } else {
      console.log('Metadata: CRITICAL: No AutoGenerated column found in report metadata.');
    }

    const physicalColumns = schema.schema || schema.columns || [];
    const physicalIdCol = physicalColumns.find(c => c.name === idCol?.name);
    if (physicalIdCol) {
      console.log(`Physical: Found column "${idCol.name}" with DB type: ${physicalIdCol.type}`);
    } else {
      console.log(`Physical: CRITICAL: Column "${idCol?.name}" NOT found in physical table!`);
    }

  } catch (error) {
    console.error('Error:', error);
  }
}

checkSheet1();
