import { queryTable } from './egdesk-helpers';

async function check() {
  const report = { id: 'a2404261-e09b-40f6-aaaf-f0b24c7a52f0', tableName: 'sheet1', columns: JSON.stringify([{name: '데이터ID', isAutoGenerated: true}]) };
  
  const allRows = await queryTable('report_row', { filters: { reportId: report.id }, limit: 10000 });
  const virtualRows = (allRows.rows || allRows).filter((r: any) => !r.isDeleted || r.isDeleted === '0' || r.isDeleted === 0 || r.isDeleted === false);
  
  const pRows = await queryTable(report.tableName, { limit: 10000 });
  const physicalRows = pRows.rows || pRows;
  
  const idColName = '데이터ID';
  const virtualIds = new Set<string>();
  virtualRows.forEach((row: any) => {
      try {
          const data = typeof row.data === 'string' ? JSON.parse(row.data) : row.data;
          if (data?.[idColName]) virtualIds.add(String(data[idColName]));
      } catch (e) {}
  });

  const physicalIds = new Set<string>();
  physicalRows.forEach((row: any) => {
      if (row[idColName]) physicalIds.add(String(row[idColName]));
  });

  let missingInPhysical: string[] = [];
  let missingInVirtual: string[] = [];

  virtualIds.forEach(id => { if (!physicalIds.has(id)) missingInPhysical.push(id); });
  physicalIds.forEach(id => { if (!virtualIds.has(id)) missingInVirtual.push(id); });

  console.log("Virtual count:", virtualRows.length);
  console.log("Physical count:", physicalRows.length);
  console.log("Only in Virtual:", missingInPhysical);
  console.log("Only in Physical:", missingInVirtual);
}

check().catch(console.error);
