'use client';

import React, { useState, useRef } from 'react';
import { Camera, Upload, Trash2, Save, Sparkles, Loader2, Plus, X } from 'lucide-react';
import { ImageReviewRow } from './ImageReviewRow';
import { analyzeImageAndExtractDataAction } from '@/app/actions/ai';
import { addRowsAction } from '@/app/actions/row';

interface Column {
  name: string;
  type: string;
  options?: string[];
  isAutoGenerated?: boolean;
}

interface AIPhotoImportSectionProps {
  reportId: string;
  columns: Column[];
  onClose: () => void;
  onStatusShow: (title: string, message: string, type: 'success' | 'error' | 'info') => void;
}

interface ReviewItem {
    id: string;
    file: File;
    preview: string;
    data: any;
    status: 'analyzing' | 'done' | 'error';
    errorMessage?: string;
}

export function AIPhotoImportSection({ reportId, columns, onClose, onStatusShow }: AIPhotoImportSectionProps) {
  const [items, setItems] = useState<ReviewItem[]>([]);
  const [isSavingAll, setIsSavingAll] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFiles = async (files: FileList | null) => {
    if (!files) return;

    const newItems: ReviewItem[] = Array.from(files).map(f => ({
        id: Math.random().toString(36).substring(7),
        file: f,
        preview: URL.createObjectURL(f),
        data: {},
        status: 'analyzing'
    }));

    setItems(prev => [...prev, ...newItems]);

    // 각 이미지 순차 분석
    for (const item of newItems) {
        try {
            const formData = new FormData();
            formData.append('image', item.file);

            // AI 추출용 컬럼 필터링 (시스템 컬럼 제외)
            const safeColumns = Array.isArray(columns) ? columns : [];
            const targetColumns = safeColumns.filter(col => {
                if (col.isAutoGenerated || (col as any).isSystem) return false;
                const name = (col.name || '').toLowerCase();
                const cleanName = (col.name || '').replace(/\s+/g, '').toLowerCase();
                if (name.startsWith('__')) return false;
                if (cleanName === 'id' || cleanName === '데이터id' || cleanName === 'dataid' || cleanName === 'did') return false;
                return true;
            });

            const result = await analyzeImageAndExtractDataAction(formData, JSON.stringify(targetColumns), reportId);
            
            if (result.success) {
                setItems(prev => {
                    const currentItem = prev.find(it => it.id === item.id);
                    if (!currentItem) return prev;

                    if (Array.isArray(result.data)) {
                        // 여러 품목이 추출된 경우: 여러 행으로 분리
                        const otherItems = prev.filter(it => it.id !== item.id);
                        const splitItems = result.data.map((d, idx) => ({
                            ...currentItem,
                            id: `${item.id}-${idx}`, // 고유 ID 생성
                            data: d,
                            status: 'done'
                        }));
                        return [...otherItems, ...splitItems];
                    } else {
                        // 단일 품목인 경우
                        return prev.map(it => 
                            it.id === item.id 
                            ? { ...it, status: 'done', data: result.data } 
                            : it
                        );
                    }
                });
            } else {
                throw new Error(result.error || '분석 실패');
            }
        } catch (error: any) {
            setItems(prev => prev.map(it => 
                it.id === item.id 
                ? { ...it, status: 'error', errorMessage: error.message || '이미지를 분석할 수 없습니다.' } 
                : it
            ));
        }
    }
  };

  const handleUpdateItemData = (id: string, newData: any) => {
    setItems(prev => prev.map(it => it.id === id ? { ...it, data: newData } : it));
  };

  const handleRemoveItem = (id: string) => {
    setItems(prev => prev.filter(it => it.id !== id));
  };

  const handleSaveAll = async () => {
    const validItems = items.filter(it => it.status === 'done');
    if (validItems.length === 0) return;

    setIsSavingAll(true);
    try {
        const rows = validItems.map(it => it.data);
        const result = await addRowsAction(reportId, rows);
        if (result.success) {
            onStatusShow('저장 완료', `${result.addedCount}건의 데이터가 추가되었습니다. (중복/오류 ${result.skippedCount}건 제외)`, 'success');
            onClose();
        } else {
            onStatusShow('저장 제한', result.error || '데이터를 저장할 수 없습니다.', 'warning');
        }
    } catch (error: any) {
        onStatusShow('저장 실패', error.message || '저장 중 오류가 발생했습니다.', 'error');
    } finally {
        setIsSavingAll(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[1000] flex items-center justify-center p-4">
      <div className="bg-white w-full max-w-5xl h-[90vh] rounded-[32px] shadow-2xl overflow-hidden flex flex-col animate-in fade-in zoom-in duration-300">
        {/* Header */}
        <div className="bg-gray-50 px-10 py-8 border-b flex items-center justify-between shrink-0">
          <div className="flex items-center gap-4">
             <div className="bg-blue-600 p-3 rounded-2xl text-white shadow-lg shadow-blue-100">
               <Sparkles size={24} />
             </div>
             <div>
               <h3 className="text-2xl font-black text-gray-900 tracking-tight">AI 사진 일괄 분석 및 등록</h3>
               <p className="text-gray-400 text-xs font-bold uppercase tracking-widest mt-1">Magic Batch Import via Gemini AI</p>
             </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white hover:shadow-md rounded-xl transition-all">
            <X size={24} className="text-gray-400" />
          </button>
        </div>

        {/* List Content */}
        <div className="flex-1 overflow-y-auto p-10 space-y-6 custom-scrollbar bg-gray-50/30">
          {items.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center space-y-6 opacity-40 py-20">
                <div className="w-24 h-24 bg-gray-200 rounded-[32px] flex items-center justify-center">
                    <Camera size={48} className="text-gray-400" />
                </div>
                <div>
                    <h4 className="text-xl font-black text-gray-900 mb-2">시작하려면 사진을 선택하세요</h4>
                    <p className="text-sm font-medium text-gray-500">여러 장의 영수증이나 명함 사진을 한꺼번에 올릴 수 있습니다.</p>
                </div>
            </div>
          ) : (
            <div className="space-y-6">
                {items.map((item) => (
                    <ImageReviewRow 
                        key={item.id}
                        imagePreview={item.preview}
                        data={item.data}
                        columns={columns}
                        status={item.status}
                        errorMessage={item.errorMessage}
                        onUpdate={(newData) => handleUpdateItemData(item.id, newData)}
                        onRemove={() => handleRemoveItem(item.id)}
                    />
                ))}

                <button 
                  onClick={() => fileInputRef.current?.click()}
                  className="w-full py-8 border-2 border-dashed border-gray-200 rounded-[28px] text-gray-400 hover:border-blue-400 hover:text-blue-600 hover:bg-blue-50 transition-all font-black uppercase tracking-widest flex items-center justify-center gap-2"
                >
                    <Plus size={24} />
                    추가 사진 업로드
                </button>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="bg-white px-10 py-8 border-t flex flex-col sm:flex-row items-center justify-between gap-6 shrink-0">
          <div className="flex flex-col gap-1">
             <p className="text-xs font-black text-gray-400 uppercase tracking-widest">
               분석 현황: {items.filter(it => it.status === 'done').length} / {items.length} 완료
             </p>
             <p className="text-[10px] font-bold text-blue-500">✨ 강조된 파란색 필드는 AI가 분석한 값입니다. 확인 후 수정할 수 있습니다.</p>
          </div>
          
          <div className="flex items-center gap-4 w-full sm:w-auto">
            {items.length === 0 && (
                <button 
                    onClick={() => fileInputRef.current?.click()}
                    className="flex-1 sm:flex-none px-10 py-4 bg-blue-600 text-white font-black rounded-2xl hover:bg-blue-700 shadow-xl shadow-blue-100 transition-all text-sm uppercase tracking-widest flex items-center gap-2"
                >
                    <Upload size={20} />
                    사진 선택하기
                </button>
            )}
            
            {items.length > 0 && (
                <>
                    <button 
                      onClick={onClose}
                      className="flex-1 sm:flex-none px-8 py-4 bg-white text-gray-600 font-bold rounded-2xl border border-gray-100 hover:bg-gray-100 transition-all text-sm"
                    >
                        취소
                    </button>
                    <button 
                      onClick={handleSaveAll}
                      disabled={isSavingAll || items.some(it => it.status === 'analyzing')}
                      className="flex-1 sm:flex-none px-12 py-4 bg-blue-600 text-white font-black rounded-2xl hover:bg-blue-700 shadow-xl shadow-blue-100 disabled:opacity-50 transition-all text-sm flex items-center gap-3"
                    >
                        {isSavingAll ? <Loader2 size={20} className="animate-spin" /> : <Save size={20} />}
                        {items.filter(it => it.status === 'done').length}건 모두 저장하기
                    </button>
                </>
            )}
            <input 
                type="file" 
                ref={fileInputRef} 
                multiple 
                accept="image/*" 
                className="hidden" 
                capture="environment"
                onChange={(e) => handleFiles(e.target.files)} 
            />
          </div>
        </div>
      </div>

      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar { width: 8px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #e2e8f0; border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #cbd5e1; }
      `}</style>
    </div>
  );
}

