'use client';

import React, { useRef, useState } from 'react';
import * as XLSX from 'xlsx';
import { Download, Upload, FileSpreadsheet, Loader2, CheckCircle2, Info } from 'lucide-react';
import { addRowsAction } from '@/app/actions/row';
import { isSubtotalRow } from '@/lib/data-utils';

interface BulkUploadProps {
  reportId: string;
  columns: any[];
  onStatusShow: (title: string, message: string, type: 'success' | 'error' | 'info') => void;
}

export function BulkUpload({ reportId, columns, onStatusShow }: BulkUploadProps) {
  const [isUploading, setIsUploading] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [previewData, setPreviewData] = useState<any[] | null>(null);
  const [filteredCount, setFilteredCount] = useState(0);
  const [selectedIndices, setSelectedIndices] = useState<Set<number>>(new Set());
  const [uploadStatus, setUploadStatus] = useState<{ type: 'success' | 'error', message: string } | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const downloadTemplate = () => {
    const headers = columns
      .filter(col => {
        if (col.isAutoGenerated || col.isSystem || col.isPrimaryKey) return false;
        const name = (col.name || '').toLowerCase();
        const cleanName = (col.name || '').replace(/\s+/g, '').toLowerCase();
        
        if (name.startsWith('__')) return false;
        if (cleanName === 'id' || cleanName === '데이터id' || cleanName === 'dataid' || cleanName === 'did') return false;
        
        return true;
      })
      .map(col => col.name);
    const ws = XLSX.utils.aoa_to_sheet([headers]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Template');
    XLSX.writeFile(wb, `template_${reportId}.xlsx`);
  };

  const processFile = (file: File) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (evt) => {
      try {
        const data = evt.target?.result;
        const workbook = XLSX.read(data, { type: 'binary' });
        const sheetName = workbook.SheetNames[0];
        const sheet = workbook.Sheets[sheetName];
        let jsonData = XLSX.utils.sheet_to_json(sheet) as any[];
        
        if (jsonData.length === 0) throw new Error('데이터가 없는 파일입니다.');
        
        // Filter subtotal/total rows
        const originalCount = jsonData.length;
        jsonData = jsonData.filter(row => !isSubtotalRow(row));
        setFilteredCount(originalCount - jsonData.length);
        
        setPreviewData(jsonData);
        setSelectedIndices(new Set(jsonData.map((_, i) => i)));
      } catch (error: any) {
        setUploadStatus({ type: 'error', message: error.message || '파일 처리 중 오류 발생' });
      }
    };
    reader.readAsBinaryString(file);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processFile(file);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) processFile(file);
  };

  const toggleSelectAll = () => {
    if (selectedIndices.size === previewData?.length) {
      setSelectedIndices(new Set());
    } else {
      setSelectedIndices(new Set(previewData?.map((_, i) => i)));
    }
  };

  const toggleSelectRow = (idx: number) => {
    const newSet = new Set(selectedIndices);
    if (newSet.has(idx)) newSet.delete(idx);
    else newSet.add(idx);
    setSelectedIndices(newSet);
  };

  const handleConfirm = async () => {
    if (!previewData || selectedIndices.size === 0) return;
    setIsUploading(true);
    setUploadStatus(null);

    const rowsToSave = previewData.filter((_, i) => selectedIndices.has(i));

    try {
      // 서버 액션에는 Date 객체 등이 포함된 클래스 타입을 전달할 수 없으므로 Plain Object로 변환
      const plainRows = JSON.parse(JSON.stringify(rowsToSave));
      const result = await addRowsAction(reportId, plainRows);
      
      if (result.addedCount === 0 && result.skippedCount > 0) {
        onStatusShow('업로드 결과', `새로 추가된 데이터가 없습니다. (중복 또는 유효성 오류로 ${result.skippedCount}건 제외)`, 'info');
      } else {
        onStatusShow('업로드 완료', `${result.addedCount}건의 데이터가 성공적으로 추가되었습니다. (중복 및 유효성 오류 ${result.skippedCount}건 제외)`, 'success');
      }
      
      setPreviewData(null);
      if (fileInputRef.current) fileInputRef.current.value = '';
      // setTimeout(() => window.location.reload(), 1500); // 팝업이 뜰 것이므로 리로드 대신 수동 닫기 유도 가능
    } catch (error: any) {
      onStatusShow('업로드 실패', error.message || '저장 중 오류가 발생했습니다.', 'error');
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="bg-white p-6 border-2 border-dashed border-gray-200 rounded-3xl space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-green-50 rounded-2xl">
            <FileSpreadsheet className="text-green-600" size={24} />
          </div>
          <div>
            <h3 className="text-sm font-black text-gray-900 tracking-tight">엑셀 일괄 추가</h3>
            <p className="text-[10px] font-bold text-gray-400 uppercase">Bulk Upload via Excel</p>
          </div>
        </div>
        {!previewData && (
          <button 
            onClick={downloadTemplate}
            className="flex items-center gap-2 px-4 py-2 bg-gray-50 text-gray-600 hover:bg-gray-100 rounded-xl transition-all text-xs font-black ring-1 ring-gray-100"
          >
            <Download size={14} />
            템플릿 다운로드
          </button>
        )}
      </div>

      {!previewData ? (
        <div className="relative group">
          <input type="file" ref={fileInputRef} onChange={handleFileChange} accept=".xlsx, .xls" className="hidden" />
          <button 
            onClick={() => fileInputRef.current?.click()}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            className={`
              w-full py-10 flex flex-col items-center justify-center gap-3 rounded-2xl border-2 border-dashed transition-all duration-200
              ${isDragging 
                ? 'bg-blue-50 border-blue-400 scale-[1.01] shadow-lg shadow-blue-100' 
                : 'bg-gray-50 border-gray-200 hover:border-blue-400 hover:bg-white'}
            `}
          >
            <div className={`p-4 rounded-full transition-colors ${isDragging ? 'bg-blue-100 text-blue-600' : 'bg-white text-gray-400 group-hover:text-blue-500'}`}>
              <Upload size={32} className={isDragging ? 'animate-bounce' : ''} />
            </div>
            <div className="text-center">
              <p className={`text-sm font-black transition-colors ${isDragging ? 'text-blue-600' : 'text-gray-500 group-hover:text-blue-600'}`}>
                {isDragging ? '이곳에 파일을 놓으세요!' : '파일을 클릭하거나 여기로 드래그하세요'}
              </p>
              <p className="text-[10px] font-bold text-gray-400 mt-1 uppercase tracking-widest">Excel files only (.xlsx, .xls)</p>
            </div>
          </button>
        </div>
      ) : (
        <div className="space-y-4 animate-in fade-in zoom-in duration-200">
            {filteredCount > 0 && (
              <div className="flex items-center gap-2 p-3 bg-amber-50 text-amber-700 rounded-2xl border border-amber-100 text-xs font-bold">
                <Info size={14} />
                <span>소계/합계 등 {filteredCount}개의 행이 자동으로 제외되었습니다.</span>
              </div>
            )}
            
            <div className="bg-gray-50 rounded-2xl p-4 overflow-hidden border border-gray-100 shadow-inner">
                <div className="flex items-center justify-between mb-3 border-b border-gray-200 pb-2">
                    <span className="text-[10px] font-black text-gray-400 uppercase tracking-wider">가져올 데이터 선택</span>
                    <span className="text-[10px] font-black bg-blue-100 text-blue-600 px-2 py-0.5 rounded-full">
                        {selectedIndices.size} / {previewData.length} 건 선택됨
                    </span>
                </div>
                <div className="max-h-[250px] overflow-y-auto overflow-x-auto custom-scrollbar">
                    <table className="w-full text-[10px] border-collapse relative">
                        <thead className="sticky top-0 bg-gray-50 shadow-sm z-10">
                            <tr>
                                <th className="py-2 px-2 text-left border-b w-8">
                                    <input 
                                        type="checkbox" 
                                        checked={selectedIndices.size === previewData.length}
                                        onChange={toggleSelectAll}
                                        className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                                    />
                                </th>
                                {Object.keys(previewData[0]).map(key => (
                                    <th key={key} className="text-left py-2 px-2 text-gray-400 border-b whitespace-nowrap">{key}</th>
                                ))}
                            </tr>
                        </thead>
                        <tbody className="bg-white">
                            {previewData.map((row, idx) => (
                                <tr 
                                    key={idx} 
                                    className={`border-b last:border-0 hover:bg-blue-50/30 transition-colors ${!selectedIndices.has(idx) ? 'opacity-40 grayscale' : ''}`}
                                    onClick={() => toggleSelectRow(idx)}
                                >
                                    <td className="py-1.5 px-2 text-center border-b">
                                        <input 
                                            type="checkbox" 
                                            checked={selectedIndices.has(idx)}
                                            onChange={() => {}} // Row click handles it
                                            className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                                        />
                                    </td>
                                    {Object.values(row).map((val: any, vIdx) => (
                                        <td key={vIdx} className="py-1.5 px-2 text-gray-600 font-bold whitespace-nowrap">{val?.toString() || '-'}</td>
                                    ))}
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            <div className="flex gap-3">
                <button 
                    onClick={() => {
                        setPreviewData(null);
                        setUploadStatus(null);
                    }}
                    className="flex-1 py-3 bg-white text-gray-400 font-black rounded-xl border border-gray-200 hover:bg-gray-50 transition-all text-xs"
                >
                    취소
                </button>
                <button 
                    onClick={handleConfirm}
                    disabled={isUploading || selectedIndices.size === 0}
                    className="flex-2 py-3 bg-blue-600 text-white font-black rounded-xl hover:bg-blue-700 shadow-xl shadow-blue-100 disabled:opacity-30 transition-all text-xs flex items-center justify-center gap-2"
                >
                    {isUploading ? <Loader2 size={16} className="animate-spin" /> : <CheckCircle2 size={16} />}
                    {selectedIndices.size}개 데이터 최종 추가
                </button>
            </div>
        </div>
      )}

      {uploadStatus && (
        <div className={`
          flex items-center gap-2 p-4 rounded-2xl animate-in fade-in slide-in-from-top-2 border
          ${uploadStatus.type === 'success' ? 'bg-green-50 text-green-700 border-green-100' : 'bg-red-50 text-red-700 border-red-100'}
        `}>
          {uploadStatus.type === 'success' ? (
              <CheckCircle2 size={18} />
          ) : (
              <div className="bg-red-500 text-white rounded-full w-5 h-5 flex items-center justify-center text-[10px] font-black shrink-0">!</div>
          )}
          <span className="text-xs font-bold leading-relaxed">{uploadStatus.message}</span>
        </div>
      )}
    </div>
  );
}

