'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { 
  Save, 
  X, 
  Calendar as CalendarIcon, 
  Hash, 
  Type, 
  CheckSquare, 
  ChevronDown, 
  AlertCircle,
  Loader2,
  Banknote,
  Mail,
  Phone,
  AlignLeft,
  LayoutList,
  Upload
} from 'lucide-react';
import { addRowAction } from '@/app/actions/row';

interface Column {
  name: string;
  type: string;
  isRequired?: boolean;
  isAutoGenerated?: boolean;
  isSystem?: boolean;
  isPrimaryKey?: boolean;
  options?: string[];
  description?: string;
}

interface DataEntryFormProps {
  reportId: string;
  columns: Column[];
  onSuccess?: (warning?: string) => void;
}

export function DataEntryForm({ reportId, columns, onSuccess }: DataEntryFormProps) {
  const router = useRouter();
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const visibleColumns = columns.filter(col => {
    // 1. 명시적 자동 생성 컬럼 제외
    if (col.isAutoGenerated || col.isSystem || col.isPrimaryKey) return false;
    
    // 2. 이름 패턴 기반 시스템 컬럼 제외 (__, id 등)
    const name = col.name.toLowerCase();
    const cleanName = col.name.replace(/\s+/g, '').toLowerCase();
    
    if (name.startsWith('__')) return false;
    if (cleanName === 'id' || cleanName === '데이터id' || cleanName === 'dataid' || cleanName === 'did') return false;
    
    return true;
  });

  const handleChange = (name: string, value: any) => {
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    try {
      const result = await addRowAction(reportId, formData);
      if (result.success) {
        setFormData({}); // 폼 초기화
        setIsSubmitting(false); // 버튼 상태 복구
        router.refresh(); // 데이터 목록 갱신

        if (onSuccess) {
           onSuccess(result.syncWarning);
        } else {
           if (result.syncWarning) {
              setError(result.syncWarning);
           }
           router.push(`/report/${reportId}`);
        }
      }
    } catch (err: any) {
      setError(err.message || '데이터 저장 중 오류가 발생했습니다.');
      setIsSubmitting(false);
    }
  };

  const renderField = (col: Column) => {
    const value = formData[col.name] || '';

    switch (col.type) {
      case 'select':
        return (
          <div className="relative">
            <select
              value={value}
              onChange={(e) => handleChange(col.name, e.target.value)}
              className="w-full px-4 pr-10 py-3 bg-gray-50 border border-gray-100 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold appearance-none cursor-pointer"
              required={col.isRequired}
            >
              <option value="">선택하세요</option>
              {col.options?.map(opt => (
                <option key={opt} value={opt}>{opt}</option>
              ))}
            </select>
            <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" size={18} />
          </div>
        );

      case 'boolean':
        return (
          <label className="flex items-center gap-3 cursor-pointer group">
            <div className={`w-12 h-6 rounded-full relative transition-all ${value ? 'bg-blue-600' : 'bg-gray-200'}`}>
                <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all ${value ? 'left-7' : 'left-1'}`} />
            </div>
            <input
              type="checkbox"
              className="hidden"
              checked={!!value}
              onChange={(e) => handleChange(col.name, e.target.checked)}
            />
            <span className="text-sm font-bold text-gray-600 group-hover:text-gray-900">{value ? '사용' : '미사용'}</span>
          </label>
        );

      case 'date':
        return (
          <div className="relative">
            <input
              type="date"
              value={value}
              onChange={(e) => handleChange(col.name, e.target.value)}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-100 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold"
              required={col.isRequired}
            />
          </div>
        );

      case 'number':
        return (
          <div className="relative">
            <input
              type="text"
              inputMode="numeric"
              value={value}
              onChange={(e) => {
                  const val = e.target.value.replace(/[^0-9.-]/g, '');
                  handleChange(col.name, val);
              }}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-100 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold"
              required={col.isRequired}
            />
          </div>
        );

      case 'currency':
        return (
          <div className="relative">
            <input
              type="text"
              inputMode="numeric"
              value={value}
              onChange={(e) => {
                  const val = e.target.value.replace(/[^0-9.,₩$¥€-]/g, '');
                  handleChange(col.name, val);
              }}
              placeholder="0"
              className="w-full px-4 py-3 bg-blue-50/30 border border-blue-100/50 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold"
              required={col.isRequired}
            />
          </div>
        );

      case 'email':
        return (
          <div className="relative">
            <input
              type="email"
              value={value}
              onChange={(e) => handleChange(col.name, e.target.value)}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-100 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold"
              required={col.isRequired}
            />
          </div>
        );

      case 'phone':
        return (
          <div className="relative">
            <input
              type="tel"
              value={value}
              onChange={(e) => handleChange(col.name, e.target.value)}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-100 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold"
              required={col.isRequired}
            />
          </div>
        );

      case 'textarea':
        return (
          <div className="relative">
            <textarea
              value={value}
              onChange={(e) => handleChange(col.name, e.target.value)}
              rows={4}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-100 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold resize-none"
              required={col.isRequired}
            />
          </div>
        );

      case 'file':
        return (
          <div className="w-full">
            <label className="flex items-center justify-center gap-3 w-full py-10 border-2 border-dashed border-gray-200 rounded-2xl cursor-pointer hover:bg-gray-50 hover:border-blue-400 transition-all text-gray-400 hover:text-blue-500 group">
              <input 
                type="button" // 실제 파일 업로드는 DynamicForm 참고하여 추후 고도화 가능하나, 일단 아이콘 통일
                className="hidden" 
              />
              <Upload size={24} className="group-hover:scale-110 transition-transform" />
              <div className="text-left">
                <p className="text-xs font-black uppercase tracking-widest leading-none mb-1">Click to upload</p>
                <p className="text-[10px] font-bold text-gray-400">Image, PDF, or Doc files</p>
              </div>
            </label>
          </div>
        );

      default:
        return (
          <div className="relative">
            <input
              type="text"
              value={value}
              onChange={(e) => handleChange(col.name, e.target.value)}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-100 rounded-xl focus:bg-white focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 outline-none transition-all font-bold"
              required={col.isRequired}
            />
          </div>
        );
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {error && (
        <div className="p-4 bg-red-50 border border-red-100 rounded-2xl flex items-center gap-3 text-red-600 text-sm font-bold animate-shake">
          <AlertCircle size={18} />
          {error}
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
        {visibleColumns.map((col) => (
          <div key={col.name} className="space-y-2">
            <label className="flex items-center gap-1.5 px-1">
              <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">{col.name}</span>
              {col.isRequired && <span className="text-red-500 font-bold">*</span>}
            </label>
            {renderField(col)}
            {col.description && <p className="text-[10px] text-gray-400 px-1 font-semibold">{col.description}</p>}
          </div>
        ))}
      </div>

      <div className="pt-8 border-t border-gray-100 flex items-center justify-between gap-4">
        <button
          type="button"
          onClick={() => router.back()}
          className="flex items-center gap-2 px-6 py-4 text-gray-400 hover:text-gray-900 font-black rounded-2xl transition-all text-xs uppercase tracking-widest"
        >
          <X size={16} />
          취소하고 돌아가기
        </button>
        <button
          type="submit"
          disabled={isSubmitting}
          className="flex items-center gap-2 px-10 py-4 bg-blue-600 text-white font-black rounded-2xl hover:bg-blue-700 transition-all shadow-xl shadow-blue-500/20 active:scale-95 disabled:opacity-50 disabled:active:scale-100 text-xs uppercase tracking-widest"
        >
          {isSubmitting ? (
            <Loader2 size={16} className="animate-spin" />
          ) : (
            <Save size={16} />
          )}
          {isSubmitting ? '제출 중...' : '제출하기'}
        </button>
      </div>
    </form>
  );
}
