'use client';

import React from 'react';
import { Trash2, Sparkles, AlertCircle } from 'lucide-react';
import { EntitySearchSelector } from './EntitySearchSelector';

interface Column {
  name: string;
  type: string;
  options?: string[];
  isAutoGenerated?: boolean;
  isMasterLinked?: boolean;
  masterTable?: string;
  lookupField?: string;
  canonicalName?: string;
  nameFields?: string[];
}

interface ImageReviewRowProps {
  imagePreview: string;
  data: any;
  columns: Column[];
  onUpdate: (newData: any) => void;
  onRemove: () => void;
  status: 'analyzing' | 'done' | 'error';
  errorMessage?: string;
}

export function ImageReviewRow({ 
  imagePreview, 
  data, 
  columns, 
  onUpdate, 
  onRemove,
  status,
  errorMessage 
}: ImageReviewRowProps) {
  const handleChange = (name: string, value: any) => {
    onUpdate({ ...data, [name]: value, _isModified: true });
  };

  return (
    <div className={`
        flex flex-col md:flex-row gap-6 p-6 bg-white border rounded-[24px] transition-all
        ${status === 'analyzing' ? 'opacity-60 animate-pulse border-blue-100 bg-blue-50/20' : 'hover:border-blue-200 hover:shadow-md'}
        ${status === 'error' ? 'border-red-100 bg-red-50/20' : ''}
    `}>
      {/* Image Preview */}
      <div className="w-full md:w-32 h-32 shrink-0 bg-gray-100 rounded-2xl overflow-hidden border border-gray-100 relative group">
        <img src={imagePreview} alt="Preview" className="w-full h-full object-cover transition-transform group-hover:scale-110" />
        <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity">
            <button onClick={() => window.open(imagePreview)} className="text-white text-[10px] font-bold underline">확대보기</button>
        </div>
        {status === 'analyzing' && (
            <div className="absolute inset-0 bg-blue-600/20 flex items-center justify-center">
                <div className="w-6 h-6 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            </div>
        )}
      </div>

      {/* Field Editor */}
      <div className="flex-1 space-y-4">
        {status === 'error' ? (
          <div className="h-full flex flex-col justify-center gap-2">
            <div className="flex items-center gap-2 text-red-600 font-bold text-sm">
                <AlertCircle size={18} />
                <span>분석 실패</span>
            </div>
            <p className="text-xs text-red-400 font-medium">{errorMessage || '이미지를 분석하는 도중 오류가 발생했습니다.'}</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {(Array.isArray(columns) ? columns : []).filter(col => {
                if (col.isAutoGenerated || (col as any).isSystem) return false;
                const name = (col.name || '').toLowerCase();
                const cleanName = (col.name || '').replace(/\s+/g, '').toLowerCase();
                if (name.startsWith('__')) return false;
                if (cleanName === 'id' || cleanName === '데이터id' || cleanName === 'dataid' || cleanName === 'did') return false;
                return true;
            }).map((col) => {
              const val = data[col.name];
              const isAiGenerated = val !== undefined && val !== null && !data._isModified;

              return (
                <div key={col.name} className="space-y-1.5 min-w-0">
                  <label className="text-[10px] font-black text-gray-400 uppercase tracking-tighter flex items-center gap-1">
                    <span className="truncate">{col.name}</span>
                    {isAiGenerated && <Sparkles size={10} className="text-blue-500 animate-pulse" />}
                  </label>
                  
                  {(() => {
                    if (col.type === 'select') {
                        return (
                            <select
                                value={val || ''}
                                onChange={(e) => handleChange(col.name, e.target.value)}
                                className={`
                                    w-full px-3 py-1.5 border rounded-lg text-xs font-bold outline-none transition-all
                                    ${isAiGenerated ? 'bg-blue-50/50 border-blue-100 text-blue-700' : 'bg-white border-gray-200 focus:border-blue-500'}
                                `}
                            >
                                <option value="">선택</option>
                                {col.options?.map(opt => (
                                    <option key={opt} value={opt}>{opt}</option>
                                ))}
                            </select>
                        );
                    }
                    
                    if (col.isMasterLinked && col.masterTable) {
                        return (
                            <EntitySearchSelector 
                                value={val}
                                entityLabel={(col.canonicalName || col.name).replace('ID', '')}
                                masterTable={col.masterTable}
                                lookupField={col.lookupField || 'name'}
                                initialName={(() => {
                                    const nameField = col.nameFields?.find(f => data[f]);
                                    return nameField ? data[nameField] : '';
                                })()}
                                isMatched={data._isMatched}
                                onChange={(id, name) => {
                                    const nameField = col.nameFields?.find(f => data[f] !== undefined);
                                    const updates: any = { [col.name]: id };
                                    if (nameField) updates[nameField] = name;
                                    onUpdate({ ...data, ...updates, _isModified: true });
                                }}
                            />
                        );
                    }

                    return (
                        <input
                            type={col.type === 'date' ? 'date' : 'text'}
                            value={val || ''}
                            onChange={(e) => handleChange(col.name, e.target.value)}
                            className={`
                                w-full px-3 py-1.5 border rounded-lg text-xs font-bold outline-none transition-all
                                ${isAiGenerated ? 'bg-blue-50/50 border-blue-100 text-blue-700' : 'bg-white border-gray-200 focus:border-blue-500'}
                            `}
                            placeholder={status === 'analyzing' ? '분석 중...' : `${col.name} 입력`}
                        />
                    );
                  })()}
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex md:flex-col justify-end gap-2">
        <button
          onClick={onRemove}
          className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-xl transition-all"
          title="목록에서 제거"
        >
          <Trash2 size={20} />
        </button>
      </div>
    </div>
  );
}
