'use client';

import React from 'react';
import { Plus, LayoutDashboard } from 'lucide-react';
import { DynamicForm } from './DynamicForm';
import { addRowAction } from '@/app/actions/row';

interface Column {
  name: string;
  type: string;
  options?: string[];
  isAutoGenerated?: boolean;
}

interface ReportDataEditorProps {
  reportId: string;
  columns: Column[];
  onStatusShow: (title: string, message: string, type: 'success' | 'error' | 'info') => void;
}

export function ReportDataEditor({ reportId, columns, onStatusShow }: ReportDataEditorProps) {
  return (
    <section className="animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header Section */}
        <div className="flex flex-col md:flex-row justify-between items-end md:items-center gap-6">
            <div className="flex items-center gap-4">
                <div className="p-3 bg-blue-600 text-white rounded-2xl shadow-xl shadow-blue-500/20">
                    <Plus size={28} strokeWidth={3} />
                </div>
                <div>
                    <h2 className="text-2xl font-black text-gray-900 tracking-tight">새로운 데이터 추가</h2>
                    <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mt-1">Direct Entry Terminal</p>
                </div>
            </div>
        </div>

        {/* Manual Entry Focused Card */}
        <div className="bg-white rounded-[40px] border border-gray-100 shadow-2xl shadow-gray-900/5 overflow-hidden group">
            <div className="bg-blue-600 px-10 py-6 text-white flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <div className="w-2.5 h-2.5 bg-white rounded-full animate-pulse shadow-[0_0_10px_rgba(255,255,255,0.8)]" />
                    <h3 className="text-sm font-black uppercase tracking-widest">방법 1. 직접 하나씩 입력하기</h3>
                </div>
                <div className="flex items-center gap-2 opacity-60">
                    <span className="text-[10px] font-black uppercase tracking-[0.2em]">Manual Entry Terminal</span>
                    <div className="h-3 w-px bg-white/30" />
                    <div className="px-2 py-0.5 bg-white/10 rounded text-[8px] font-black tracking-tighter uppercase whitespace-nowrap">Live Auth</div>
                </div>
            </div>
            
            <div className="p-10 md:p-14">
                <DynamicForm 
                    columns={columns.filter(col => {
                        if (col.isAutoGenerated || (col as any).isSystem || (col as any).isPrimaryKey) return false;
                        const name = col.name.toLowerCase();
                        const cleanName = col.name.replace(/\s+/g, '').toLowerCase();
                        if (name.startsWith('__')) return false;
                        if (cleanName === 'id' || cleanName === '데이터id' || cleanName === 'dataid' || cleanName === 'did') return false;
                        return true;
                    })} 
                    onStatusShow={onStatusShow}
                    onSubmit={async (data: any) => {
                        try {
                            await addRowAction(reportId, data);
                            onStatusShow('저장 완료', '데이터가 성공적으로 추가되었습니다.', 'success');
                        } catch (error: any) {
                            onStatusShow('저장 실패', error.message || '데이터 저장 중 오류가 발생했습니다.', 'error');
                        }
                    }} 
                />
            </div>
        </div>

        {/* Floating Info Pill */}
        <div className="flex items-center justify-center">
            <div className="flex items-center gap-4 px-6 py-2.5 bg-white border border-gray-100 rounded-2xl shadow-sm text-[10px] font-black text-gray-400 uppercase tracking-widest">
                <LayoutDashboard size={14} className="text-blue-500" />
                <span>대량의 데이터는 상단의 <span className="text-green-600">BULK UPLOAD</span> 또는 <span className="text-indigo-600">AI 사진 등록</span> 기능을 이용하세요</span>
            </div>
        </div>
      </div>
    </section>
  );
}

