import { queryTable, updateRows, getTableSchema } from './egdesk-helpers.ts';
import { SYSTEM_COLUMN_LIST } from './lib/constants/db.ts';
import { DbSyncService } from './lib/services/db-sync-service.ts';

async function migrate() {
    try {
        console.log("Starting System Columns Migration (Blue-Green)...");

        // 1. 모든 보고서(테이블) 조회
        const reports = await queryTable('dashboard_master');
        console.log(`Found ${reports.length} reports to check.`);

        for (const report of reports) {
            console.log(`\n--- Processing Report: ${report.name} (${report.reportId}) ---`);

            // 2. dashboard_master의 columns 업데이트
            let columns = [];
            try {
                columns = JSON.parse(report.columns);
            } catch (e) {
                console.error(`Failed to parse columns for ${report.reportId}`);
                continue;
            }

            const missingInMeta = SYSTEM_COLUMN_LIST.filter(sc => !columns.some((c: any) => c.name === sc.name));
            let finalColumns = columns;
            
            if (missingInMeta.length > 0) {
                finalColumns = [...columns, ...missingInMeta];
                await updateRows('dashboard_master', { columns: JSON.stringify(finalColumns) }, { filters: { reportId: String(report.reportId) } });
                console.log(`Updated metadata columns for ${report.reportId}.`);
            } else {
                console.log(`Metadata columns already up to date for ${report.reportId}.`);
            }

            // 3. 물리 테이블 마이그레이션 (Blue-Green)
            if (report.tableName) {
                try {
                    const physicalSchema = await getTableSchema(report.tableName);
                    const isMissingInPhysical = SYSTEM_COLUMN_LIST.some(sc => !physicalSchema.some((c: any) => c.name === sc.name));

                    if (isMissingInPhysical) {
                        console.log(`Physical table ${report.tableName} needs migration. Starting Blue-Green migration...`);
                        
                        // Blue-Green Migration 실행
                        const newTableName = await DbSyncService.migratePhysicalTable(
                            report.reportId,
                            report.name,
                            report.tableName,
                            columns, // old columns
                            finalColumns // new columns
                        );

                        console.log(`Migration successful. New table: ${newTableName}`);

                        // 4. 데이터 동기화 (dashboard_data -> physical table)
                        console.log(`Syncing system column data for ${newTableName}...`);
                        const virtualRows = await queryTable('dashboard_data', { filters: { reportId: String(report.reportId) } });
                        
                        for (const vRow of virtualRows) {
                            try {
                                const rowData = JSON.parse(vRow.data);
                                const idCol = finalColumns.find((c: any) => c.isAutoGenerated);
                                const filterKey = idCol?.name || finalColumns[0].name;
                                const filterValue = rowData[filterKey];

                                if (filterValue) {
                                    await updateRows(newTableName, {
                                        __created_at: vRow.createdAt,
                                        __updated_at: vRow.updatedAt,
                                        __creator_id: vRow.creatorId
                                    }, { filters: { [filterKey]: String(filterValue) } });
                                }
                            } catch (e) {
                                // console.error(`Failed to sync row for ${newTableName}`);
                            }
                        }
                        console.log(`Sync completed for ${newTableName}.`);
                    } else {
                        console.log(`Physical table ${report.tableName} already has system columns.`);
                    }
                } catch (e: any) {
                    console.error(`Error processing physical table ${report.tableName}:`, e.message);
                }
            }
        }

        console.log("\nMigration completed successfully!");

    } catch (err: any) {
        console.error("Migration failed:", err.message);
        if (err.stack) console.error(err.stack);
    }
}

migrate();
