import { queryTable, updateRows, insertRows, deleteRows, deleteTable } from '@/egdesk-helpers';
import { DbSyncService } from './db-sync-service';
import { ValidationService } from './validation-service';
import { HistoryService } from './history-service';
import { revalidatePath } from 'next/cache';
import { getNowKST, formatToKST } from '../data-utils';

export class ReportService {
    /**
     * 보고서의 데이터를 새로운 스키마에 맞춰 변환하고 이관합니다.
     */
    static async migrateReportData(
        reportId: string,
        tableName: string | undefined,
        oldColumns: any[],
        newColumns: any[]
    ) {
        // 이름 변경 맵핑 (oldName -> newName) 구성
        const renameMap: Record<string, string> = {};
        const renamedCols = newColumns.filter(newCol => newCol.originalName && newCol.originalName !== newCol.name);
        renamedCols.forEach(col => {
            renameMap[col.originalName] = col.name;
        });

        // [Soft Delete] 삭제되지 않은 데이터만 마이그레이션 대상
        const allRows = await queryTable('dashboard_data', { filters: { reportId: String(reportId), __is_deleted: '0' } });
        const validNewKeys = new Set(newColumns.map(c => c.name));

        for (const row of allRows) {
            const oldRowData = JSON.parse(row.data);
            const newRowData: any = {};
            let hasChanged = false;

            // 1. 키 이름 및 삭제된 컬럼 처리
            for (const oldKey in oldRowData) {
                const val = oldRowData[oldKey];
                const targetKey = renameMap[oldKey] || oldKey;

                if (!validNewKeys.has(targetKey)) {
                    hasChanged = true;
                    continue;
                }

                newRowData[targetKey] = val;
                if (targetKey !== oldKey) hasChanged = true;
            }

            // 2. 새로운 스키마 기준 타입 캐스팅
            for (const col of newColumns) {
                const val = newRowData[col.name];
                if (val === undefined || val === null || val === '') continue;

                let newVal = val;
                try {
                    if (col.type === 'number' || col.type === 'currency') {
                        const cleanVal = String(val).replace(/[^0-9.-]/g, '').trim();
                        if (!isNaN(Number(cleanVal)) && cleanVal !== '') newVal = Number(cleanVal);
                    } else if (col.type === 'date') {
                        newVal = this.castDateValue(val);
                    } else if (col.type === 'boolean') {
                        newVal = (val === 'true' || val === '1' || val === 1 || val === true);
                    }
                } catch (e) {}

                if (newRowData[col.name] !== newVal) {
                    newRowData[col.name] = newVal;
                    hasChanged = true;
                }
            }

            if (hasChanged) {
                const updatedDataStr = JSON.stringify(newRowData);
                await updateRows('dashboard_data', { data: updatedDataStr, updatedAt: getNowKST() }, { filters: { id: String(row.id) } });

                // 물리 테이블 동기화
                if (tableName) {
                    const idCol = newColumns.find((c: any) => c.isAutoGenerated);
                    if (idCol && newRowData[idCol.name]) {
                        await DbSyncService.syncToPhysicalTable(tableName, newRowData, newColumns, { [idCol.name]: String(newRowData[idCol.name]) });
                    }
                }
            }
        }
    }

    /**
     * 날짜 값 캐스팅 (엑셀 시리얼 날짜 지원)
     */
    private static castDateValue(val: any): string {
        if (!isNaN(Number(val)) && String(val).trim() !== '') {
            const serialNum = Number(val);
            if (serialNum > 10000 && serialNum < 100000) {
                const dateInfo = new Date(Math.floor(serialNum - 25569) * 86400 * 1000);
                return !isNaN(dateInfo.getTime()) ? formatToKST(dateInfo).split('T')[0] : String(val);
            }
        }
        const d = new Date(val);
        return !isNaN(d.getTime()) ? formatToKST(d) : String(val);
    }

    /**
     * [Soft Delete] 보고서를 논리적으로 삭제하고 데이터를 보존합니다.
     */
    static async softDeleteReport(reportId: string, tableName?: string, userId: string = 'system') {
        const timestamp = getNowKST();
        
        // 1. 마스터 정보 논리 삭제
        await updateRows('dashboard_master', { 
            __is_deleted: 1, 
            __deleted_at: timestamp,
            __modifier_id: userId
        }, { filters: { id: String(reportId) } });

        // 2. 가상 데이터 논리 삭제
        await updateRows('dashboard_data', { 
            __is_deleted: 1, 
            __deleted_at: timestamp 
        }, { filters: { reportId: String(reportId) } });

        // 3. 물리 테이블 데이터 논리 삭제 (테이블 자체는 보존)
        if (tableName) {
            try {
                await updateRows(tableName, { 
                    __is_deleted: 1, 
                    __deleted_at: timestamp,
                    __modifier_id: userId
                }, {}); // 모든 행 대상
            } catch (err) {
                console.error(`[ReportService] Failed to soft delete physical table ${tableName}:`, err);
            }
        }

        // 4. 감사 로그 기록
        await HistoryService.recordHistory(String(reportId), 'active', 'soft-deleted', 'DELETE', userId);
        
        revalidatePath('/dashboard');
        revalidatePath('/admin');
    }

    /**
     * 보고서를 영구 삭제합니다. (주의: 이 기능은 관리자 도구 등에서만 제한적으로 사용 권장)
     */
    static async permanentDeleteReport(reportId: string, tableName?: string) {
        await deleteRows('dashboard_data', { filters: { reportId: String(reportId) } });
        if (tableName) {
            try {
                await deleteTable(tableName);
            } catch (err) {}
        }
        await deleteRows('dashboard_master', { filters: { id: String(reportId) } });
    }
}
