import crypto from 'crypto';
import { queryTable, updateRows, insertRows } from '@/egdesk-helpers';
import { ValidationService } from './validation-service';
import { HistoryService } from './history-service';
import { DbSyncService } from './db-sync-service';

export class RowService {
    /**
     * 데이터 행의 중복 여부를 판단하기 위한 해시값을 생성합니다.
     */
    static async generateContentHash(rowData: any, columns: any[]) {
        const isUnique = (col: any) => col.isUnique === true || String(col.isUnique) === 'true' || Number(col.isUnique) === 1 || String(col.isUnique) === '1';
        
        const uniqueCols = columns.filter(c => isUnique(c));
        const targetCols = uniqueCols.length > 0 ? uniqueCols : columns.filter(c => !c.isAutoGenerated);
        
        const sortedKeys = targetCols.map(c => c.name).sort();
        const hashSource = sortedKeys.map(key => `${key}:${rowData[key] === undefined || rowData[key] === null ? '' : rowData[key]}`).join('|');
        
        return crypto.createHash('sha256').update(hashSource).digest('hex');
    }

    /**
     * 보고서의 다음 자동 생성 일련번호를 계산합니다.
     */
    static async calculateNextSerial(reportId: string, tableName?: string, idColumnName?: string): Promise<number> {
        let currentSerial = 0;

        // 1. 물리 테이블에서 최대값 확인
        if (tableName && idColumnName) {
            try {
                const rows: any = await queryTable(tableName, { limit: 100000 });
                const rowsArray = Array.isArray(rows) ? rows : (rows?.rows || []);
                rowsArray.forEach((r: any) => {
                    const did = r[idColumnName];
                    if (did && typeof did === 'string') {
                        const num = parseInt(did.replace(/[^0-9]/g, ''), 10);
                        if (!isNaN(num) && num > currentSerial) currentSerial = num;
                    }
                });
            } catch (e) {}
        }

        // 2. 가상 테이블에서 최대값 확인 (물리 테이블이 없거나 실패한 경우)
        if (currentSerial === 0) {
            try {
                const results: any = await queryTable('dashboard_data', { filters: { reportId: String(reportId) }, limit: 100000 });
                const rows = Array.isArray(results) ? results : (results?.rows || []);
                rows.forEach((r: any) => {
                    try {
                        const data = JSON.parse(r.data);
                        const did = data[idColumnName || ''];
                        if (did && typeof did === 'string') {
                            const num = parseInt(did.replace(/[^0-9]/g, ''), 10);
                            if (!isNaN(num) && num > currentSerial) currentSerial = num;
                        }
                    } catch (e) {}
                });
            } catch (e) {}
        }

        return currentSerial + 1;
    }

    /**
     * 단일 행 데이터를 가상 및 물리 테이블에 최종 저장합니다.
     */
    static async saveRow(
        reportId: string,
        tableName: string | undefined,
        columns: any[],
        finalData: any,
        hash: string,
        creatorId: string
    ) {
        // 1. 물리 테이블 동기화
        if (tableName) {
            await DbSyncService.insertToPhysicalTable(tableName, [finalData], columns);
        }

        // 2. 가상 테이블 저장
        const result = await insertRows('dashboard_data', [{
            reportId,
            data: JSON.stringify(finalData),
            contentHash: hash,
            creatorId: creatorId,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            isDeleted: 0
        }]);

        if (!result?.success) {
            throw new Error(result?.error || '데이터 저장 실패');
        }

        return { success: true };
    }
}
