export interface ColumnDefinition {
    name: string;
    type: 'string' | 'number' | 'currency' | 'date' | 'select' | 'boolean' | 'textarea';
    isRequired?: boolean;
    isAutoGenerated?: boolean;
    autoPrefix?: string;
    options?: string | string[];
    isUnique?: boolean;
}

export class ValidationService {
    /**
     * 보고서 컬럼 정의에 따라 행 데이터의 유효성을 검사합니다.
     */
    static validateRowData(rowData: any, columns: ColumnDefinition[]): { isValid: boolean; error?: string; cleanedData: any } {
        const cleanedData = { ...rowData };

        for (const col of columns) {
            const val = rowData[col.name];
            
            // 자동 생성 필드 및 시스템 필드는 검증 제외
            if (col.isAutoGenerated || col.isSystem || col.name.startsWith('__')) continue;

            // 1. 필수값 체크
            if (col.isRequired && (val === undefined || val === null || val === '')) {
                // 숫자인 경우 0은 허용
                if (val !== 0) {
                    return { isValid: false, error: `'${col.name}' 필드는 필수입니다.`, cleanedData };
                }
            }

            // 2. Select 옵션 체크
            if (col.type === 'select' && col.options && val !== '' && val !== null && val !== undefined) {
                const rawOptions = col.options;
                const optionsList = Array.isArray(rawOptions) ? rawOptions : String(rawOptions).split(',').map(s => s.trim()).filter(Boolean);
                if (!optionsList.includes(String(val).trim())) {
                    return { isValid: false, error: `'${col.name}' 필드의 값 '${val}'은(는) 허용된 목록(${optionsList.join(', ')})에 없습니다.`, cleanedData };
                }
            }

            // 3. 숫자/통화 형식 체크 및 변환
            if ((col.type === 'number' || col.type === 'currency') && val !== '' && val !== null && val !== undefined) {
                const sVal = String(val);
                const cleanVal = sVal.replace(/[^0-9.-]/g, '').trim();
                
                if (cleanVal === '' && col.isRequired) {
                     return { isValid: false, error: `'${col.name}' 필드에 유효한 숫자를 입력해 주세요.`, cleanedData };
                }

                if (cleanVal !== '' && isNaN(Number(cleanVal))) {
                    return { isValid: false, error: `'${col.name}' 필드에는 숫자만 입력 가능합니다.`, cleanedData };
                }
                
                if (cleanVal !== '') {
                    cleanedData[col.name] = Number(cleanVal);
                }
            }
            
            // 4. 날짜 형식 처리
            if (col.type === 'date' && val) {
                let dateStr = String(val).trim();
                // '2024.01.01' -> '2024-01-01'
                dateStr = dateStr.replace(/\./g, '-');
                // '2024년 01월 01일' -> '2024-01-01'
                dateStr = dateStr.replace(/년|월/g, '-').replace(/일/g, '').replace(/\s+/g, '');
                
                const d = new Date(dateStr);
                if (isNaN(d.getTime())) {
                    if (col.isRequired) {
                        return { isValid: false, error: `'${col.name}' 필드에 유효한 날짜를 입력해 주세요. (입력값: ${val})`, cleanedData };
                    }
                } else {
                    // YYYY-MM-DD 형식으로 정규화
                    cleanedData[col.name] = d.toISOString().split('T')[0];
                }
            }
        }

        return { isValid: true, cleanedData };
    }
}
