'use server';

import { revalidatePath } from 'next/cache';
import { 
    listTables,
    queryTable,
    createTable,
    insertRows
} from '@/egdesk-helpers';
import { getSessionAction } from './auth';
import { parseExcelWorkbook } from '@/lib/excel-parser';
import { normalizeTableName, mapToPhysicalType } from '@/lib/db-utils';
import { notifyBulkUpload } from '@/lib/notifications';
import { SYSTEM_COLUMN_LIST } from '@/lib/constants/db';
import fs from 'fs/promises';
import path from 'path';

export async function uploadFileAction(formData: FormData) {
    const file = formData.get('file') as File;
    if (!file) throw new Error('파일이 없습니다.');

    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);

    const uploadDir = path.join(process.cwd(), 'public', 'uploads');
    try {
        await fs.access(uploadDir);
    } catch {
        await fs.mkdir(uploadDir, { recursive: true });
    }

    const uniqueName = `${Date.now()}-${file.name.replace(/\s+/g, '_')}`;
    const filePath = path.join(uploadDir, uniqueName);
    await fs.writeFile(filePath, buffer);

    return { url: `/uploads/${uniqueName}`, name: file.name };
}

export async function uploadExcelAction(formData: FormData, userId: string) {
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');

  const file = formData.get('file') as File;
  const configsJson = formData.get('configsJson') as string;
  if (!file) throw new Error('파일이 없습니다.');

  const buffer = Buffer.from(await file.arrayBuffer());
  const configs = configsJson ? JSON.parse(configsJson) : [];
  
  let sheetResults: any[] = [];
  const hasAiConfig = configs.some((c: any) => c.isAiGenerated);

  if (hasAiConfig) {
      // AI 모드: 클라이언트에서 분석 완료된 데이터(initialRows)를 바로 사용
      sheetResults = configs.map((config: any) => {
          const columns = config.selectedFields.map((f: any) => ({
              name: f.name,
              type: f.type,
              isRequired: f.isRequired,
              isAutoGenerated: f.id === '__data_id__'
          }));

          const rows = (config.initialRows || []).map((row: any, idx: number) => {
              const dataIdField = config.selectedFields.find((f: any) => f.id === '__data_id__');
              const dataIdName = dataIdField ? dataIdField.name : '데이터ID';
              
              const rowObj = { ...row };
              if (!rowObj[dataIdName]) {
                  rowObj[dataIdName] = `AI-${(idx+1).toString().padStart(6, '0')}`;
              }
              return rowObj;
          });

          return {
              sheetName: config.sheetName || config.tableName,
              tags: config.tags,
              tables: [{
                  name: config.tableName,
                  columns: columns,
                  rows: rows
              }]
          };
      });
  } else {
      // 기존 엑셀 파싱 모드
      sheetResults = parseExcelWorkbook(buffer, configs).map((res, idx) => ({
          ...res,
          tags: configs[idx]?.tags
      }));
  }
  console.log(`[Uploader] Processing ${sheetResults.length} logical sheets.`);

  let existingTables: string[] = [];
  try {
      const res = await listTables();
      const sysTables = (res?.tables || []).map((t: any) => t.tableName.toLowerCase());
      
      const reportRes = await queryTable('dashboard_master', { limit: 10000 });
      const reportRows = Array.isArray(reportRes) ? reportRes : (reportRes?.rows || []);
      const virtualTables = reportRows
        .map((r: any) => r.tableName?.toLowerCase())
        .filter(Boolean);

      existingTables = Array.from(new Set([...sysTables, ...virtualTables]));
  } catch (err) {
      console.error('Failed to list tables for duplicate check:', err);
  }

  const uploadStats = {
    totalRejected: 0,
    rejectedReasons: [] as string[]
  };

  for (const sheet of sheetResults) {
    for (const table of sheet.tables) {
      if (table.columns.length === 0) continue; 

      // reportId will be captured from insertRows result
      let reportId: string = '';
      const basePhysicalName = normalizeTableName(table.name);
      let physicalTableName = basePhysicalName;
      let counter = 1;
      
      while (existingTables.includes(physicalTableName)) {
          physicalTableName = `${basePhysicalName}_${counter}`;
          counter++;
      }
      existingTables.push(physicalTableName);

      try {
        const schema = [
          ...table.columns.map(col => {
            if (!col.id) {
              col.id = `col_${Date.now().toString(36)}_${Math.random().toString(36).substring(2, 7)}`;
            }
            return {
              name: col.name,
              type: mapToPhysicalType(col.type),
              notNull: col.isRequired
            };
          }),
          ...SYSTEM_COLUMN_LIST.map(col => ({
            name: col.name,
            type: mapToPhysicalType(col.type),
            notNull: col.isRequired
          }))
        ];

        const uniqueKeys = table.columns
          .filter(col => col.isAutoGenerated || col.isUnique)
          .map(col => col.name);

        await createTable(table.name, schema, {
          tableName: physicalTableName,
          description: `Created from Excel: ${file.name} - ${sheet.sheetName}`,
          uniqueKeyColumns: uniqueKeys.length > 0 ? uniqueKeys : undefined
        });
      } catch (err: any) {
        throw new Error(`물리적 테이블('${physicalTableName}') 생성에 실패하여 업로드가 취소되었습니다. 원인: ${err.message || '알 수 없음'}`);
      }

      const validRows: any[] = [];
      table.rows.forEach((row, idx) => {
        let isRowValid = true;
        const missingFields: string[] = [];
        
        table.columns.forEach(col => {
           if (col.isRequired) {
              const val = row[col.name];
              if (val === undefined || val === null || val === '') {
                 isRowValid = false;
                 if (col.name !== '__data_id__') {
                    missingFields.push(col.name);
                 }
              }
           }
        });
        
        if (isRowValid) {
           // 시스템 컬럼 데이터 할당
           const now = new Date().toISOString();
           const enrichedRow = {
              ...row,
              __created_at: now,
              __updated_at: now,
              __creator_id: userId
           };
           validRows.push(enrichedRow);
        } else {
           uploadStats.totalRejected++;
           if (uploadStats.rejectedReasons.length < 10) {
              uploadStats.rejectedReasons.push(`[${table.name}] 엑셀 ${idx + 2}번째 줄 - 누락: ${missingFields.length > 0 ? missingFields.join(', ') : '필수값'}`);
           }
        }
      });

      table.rows = validRows;

      let maxSerial = table.rows.length;
      const autoCol = table.columns.find((c: any) => c.isAutoGenerated);
      if (autoCol) {
          table.rows.forEach(r => {
              const val = r[autoCol.name];
              if (val && typeof val === 'string') {
                  const num = parseInt(val.replace(/[^0-9]/g, ''), 10);
                  if (!isNaN(num) && num > maxSerial) {
                      maxSerial = num;
                  }
              }
          });
      }

      const reportInsertRes = await insertRows('dashboard_master', [{
        reportId: `rep-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
        name: table.name,
        sheetName: sheet.sheetName,
        tableName: physicalTableName, 
        columns: JSON.stringify([...table.columns, ...SYSTEM_COLUMN_LIST]),
        uiConfig: JSON.stringify({ tags: (sheet.tags && sheet.tags.length > 0) ? sheet.tags : ["Excel"] }),
        ownerId: userId,
        createdAt: new Date().toISOString(),
        isDeleted: 0, 
        lastSerial: maxSerial 
      }]);

      // Register in table_master (Physical Registry)
      await insertRows('table_master', [{
        tableName: physicalTableName,
        displayName: table.name,
        category: 'EXCEL',
        schema: JSON.stringify(table.columns),
        rowCount: table.rows.length,
        createdAt: new Date().toISOString()
      }]).catch(() => {});
      const insertedReport = Array.isArray(reportInsertRes) ? reportInsertRes[0] : (reportInsertRes.rows?.[0] || reportInsertRes);
      reportId = String(insertedReport.id);

      if (table.rows.length > 0) {
        const vRes = await insertRows('dashboard_data', table.rows.map(row => ({
          // id: auto-generated,
          reportId: reportId,
          data: JSON.stringify(row),
          creatorId: userId,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          isDeleted: 0
        })));

        if (!vRes?.success) {
            throw new Error(`Virtual table insertion failed: ${vRes?.error || JSON.stringify(vRes)}`);
        }

        try {
          await insertRows(physicalTableName, table.rows);
        } catch (err) {
          console.error(`Failed to insert rows into physical table ${physicalTableName}:`, err);
        }

        notifyBulkUpload(table.name, user.fullName || user.username, table.rows.length, table.rows[0], table.columns, null).catch(console.error);
      }
    }
  }

  revalidatePath('/');
  return { 
    success: true, 
    totalRejected: uploadStats.totalRejected, 
    rejectedReasons: uploadStats.rejectedReasons 
  };
}
