'use server';

import { revalidatePath } from 'next/cache';
import { 
    queryTable, 
    insertRows, 
    updateRows, 
    deleteRows
} from '@/egdesk-helpers';
import { 
    checkReportAuthorization
} from './shared';
import { getMasterRecords } from './report';
import { getSessionAction } from './auth';
import { notifyNewDataRow, notifyBulkUpload, logActivity } from '@/lib/notifications';
import { triggerWorkflow } from '@/lib/workflow/engine';
import { ValidationService } from '@/lib/services/validation-service';
import { HistoryService } from '@/lib/services/history-service';
import { DbSyncService } from '@/lib/services/db-sync-service';
import { RowService } from '@/lib/services/row-service';

/**
 * 보고서에 새로운 데이터를 추가합니다.
 */
export async function addRowAction(reportId: string, rowData: any) {
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');
  
  const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
  if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

  const reports: any = await getMasterRecords(String(reportId));
  const report = reports[0];
  if (!report) throw new Error('보고서를 찾을 수 없습니다.');

  const columns = JSON.parse(report.columns);
  
  // 1. 유효성 검사 및 데이터 정제
  const { isValid, error, cleanedData } = ValidationService.validateRowData(rowData, columns);
  if (!isValid) throw new Error(error);

  let syncWarning: string | null = null;
  const uiConfig = report.uiConfig ? JSON.parse(report.uiConfig) : {};
  const uniqueKeyColumns = uiConfig.uniqueKeyColumns;
  
  const hash = await RowService.generateContentHash(cleanedData, columns, uniqueKeyColumns);

  // 2. 중복 체크 (Soft Delete 고려)
  try {
      const existingRows: any = await queryTable('dashboard_data', {
          filters: { reportId: String(reportId), contentHash: String(hash), __is_deleted: '0' }
      });
      if (existingRows.length > 0) throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
  } catch (err: any) {
      if (err.message.includes('중복 방지')) throw err;
      console.warn(`중복 체크 스킵: ${err.message}`);
  }

  // 3. 자동 ID 생성
  const idCol = columns.find((c: any) => c.isAutoGenerated);
  if (idCol) {
      const nextSerial = await RowService.calculateNextSerial(reportId, report.tableName, idCol.name);
      cleanedData[idCol.name] = `${idCol.autoPrefix || 'DID-'}${nextSerial.toString().padStart(6, '0')}`;
      updateRows('dashboard_master', { lastSerial: nextSerial }, { filters: { reportId: String(reportId) } }).catch(() => {});
  }
  
  // 시스템 컬럼 데이터 할당 (표준 규격)
  const now = new Date().toISOString();
  cleanedData.__created_at = now;
  cleanedData.__updated_at = now;
  cleanedData.__creator_id = user.id;
  cleanedData.__modifier_id = user.id;
  cleanedData.__is_deleted = 0;

  // 4. 저장 (물리 + 가상 테이블)
  const saveResult: any = await RowService.saveRow(reportId, report.tableName, columns, cleanedData, hash, user.id);
  if (saveResult?.syncError) {
      syncWarning = saveResult.syncError;
  }

  const firstCol = columns.find((c: any) => !c.isAutoGenerated) || columns[0];
  const summary = firstCol ? cleanedData[firstCol.name] : 'N/A';

  logActivity({
      userId: user.id,
      title: `[${report.name}] 데이터 등록`,
      message: `[${summary}] 항목을 새롭게 등록했습니다.`,
      link: `/report/${reportId}`,
      type: 'ACTIVITY'
  }).catch(console.error);
  triggerWorkflow(reportId, cleanedData, user.id).catch(console.error);

  revalidatePath(`/report/${reportId}`);
  return { success: true, syncWarning };
}

/**
 * 대량의 데이터를 한꺼번에 추가합니다. (예: 엑셀 업로드)
 */
export async function addRowsAction(reportId: string, rows: any[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await getMasterRecords(String(reportId));
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');
  
    const columns = JSON.parse(report.columns);
    const idCol = columns.find((c: any) => c.isAutoGenerated);
    let nextSerial = await RowService.calculateNextSerial(reportId, report.tableName, idCol?.name);

    const cleanedRowsToInsert = [];
    let skippedCount = 0;
    
    // 기존 해시값 로드 (중복 방지용 - 삭제되지 않은 것만)
    const existingRows = await queryTable('dashboard_data', { filters: { reportId: String(reportId), __is_deleted: '0' } });
    const existingHashes = new Set(existingRows.map((r: any) => r.contentHash));

    const uiConfig = report.uiConfig ? JSON.parse(report.uiConfig) : {};
    const uniqueKeyColumns = uiConfig.uniqueKeyColumns;

    console.log(`>>> [addRowsAction] Starting save for reportId: ${reportId}, rows: ${rows.length}`);
    const validationErrors: string[] = [];

    for (let i = 0; i < rows.length; i++) {
        const rowData = rows[i];
        const { isValid, error, cleanedData } = ValidationService.validateRowData(rowData, columns);
        if (!isValid) { 
            const msg = `${i + 1}번 행 유효성 검사 실패: ${error}`;
            console.warn(`>>> [addRowsAction] ${msg}`, rowData);
            validationErrors.push(msg);
            skippedCount++; 
            continue; 
        }

        const hash = await RowService.generateContentHash(cleanedData, columns, uniqueKeyColumns);
        if (existingHashes && existingHashes.size > 0 && existingHashes.has(hash)) { 
            const msg = `${i + 1}번 행 중복: 이미 등록된 데이터입니다. (해시: ${hash.substring(0, 8)}...)`;
            console.warn(`>>> [addRowsAction] ${msg}`);
            validationErrors.push(msg);
            skippedCount++; 
            continue; 
        }

        if (idCol) {
            cleanedData[idCol.name] = `${idCol.autoPrefix || 'DID-'}${nextSerial.toString().padStart(6, '0')}`;
            nextSerial++;
        }

        const now = new Date().toISOString();
        cleanedData.__created_at = now;
        cleanedData.__updated_at = now;
        cleanedData.__creator_id = user.id;
        cleanedData.__modifier_id = user.id;
        cleanedData.__is_deleted = 0;

        cleanedRowsToInsert.push({
            reportId: String(reportId),
            data: cleanedData,
            contentHash: hash
        });
        if (existingHashes) existingHashes.add(hash);
    }

    if (cleanedRowsToInsert.length > 0) {
        // ... (동일한 저장 로직)
        if (report.tableName) {
            const physicalResult = await DbSyncService.insertToPhysicalTable(report.tableName, cleanedRowsToInsert.map(r => r.data), columns);
            if (!physicalResult.success) {
                throw new Error(`물리 테이블 저장 실패: ${physicalResult.error}`);
            }
        }

        const virtualRows = cleanedRowsToInsert.map(r => {
            const vRow: any = {
                reportId: r.reportId,
                data: JSON.stringify(r.data),
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                __created_at: new Date().toISOString(),
                __updated_at: new Date().toISOString(),
                __creator_id: user.id,
                __modifier_id: user.id,
                __is_deleted: 0
            };
            if (existingRows && existingRows.length > 0 && 'contentHash' in existingRows[0]) {
                vRow.contentHash = r.contentHash;
            }
            return vRow;
        });

        await insertRows('dashboard_data', virtualRows);
        
        if (idCol) {
            await updateRows('dashboard_master', { lastSerial: nextSerial - 1 }, { filters: { reportId: String(reportId) } });
        }
    } else if (skippedCount > 0) {
        return { 
            success: false, 
            error: validationErrors.length > 0 ? validationErrors.join('\n') : '모든 데이터가 중복되어 제외되었습니다.'
        };
    }
  
    notifyBulkUpload(report.name, user.fullName || user.username, cleanedRowsToInsert.length, cleanedRowsToInsert[0]?.data, columns, report.slackWebhookUrl).catch(console.error);
    logActivity({
        userId: user.id,
        title: `[${report.name}] 데이터 등록`,
        message: `${cleanedRowsToInsert.length}건의 데이터를 등록했습니다.`,
        link: `/report/${reportId}`,
        type: 'ACTIVITY'
    }).catch(console.error);

    revalidatePath('/report/' + reportId);
    return { success: true, addedCount: cleanedRowsToInsert.length, skippedCount };
}

/**
 * 단일 행 데이터를 수정합니다.
 */
export async function updateSingleRowAction(reportId: string, rowId: string, newData: any) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await getMasterRecords(String(reportId));
    const report = reports[0];
    const columns = JSON.parse(report.columns);
    const rows = await queryTable('dashboard_data', { filters: { id: String(rowId) } });
    const row = rows[0];

    if (user.role === 'VIEWER' && row.creatorId !== user.id) {
        throw new Error('본인이 작성하지 않은 데이터는 수정할 수 없습니다.');
    }
    
    // 시스템 컬럼 업데이트
    const now = new Date().toISOString();
    newData.__updated_at = now;
    newData.__modifier_id = user.id;

    // 1. 가상 테이블 업데이트
    const updatedDataStr = JSON.stringify(newData);
    const updateRes = await updateRows('dashboard_data', {
        data: updatedDataStr,
        updatedAt: now,
        updaterId: user.id
    }, { filters: { id: String(rowId) } });

    if (updateRes && typeof updateRes === 'object' && updateRes.success === false) {
        throw new Error(`가상 테이블 업데이트 실패: ${updateRes.error}`);
    }

    // 2. 이력 기록
    await HistoryService.recordHistory(rowId, row.data, updatedDataStr, 'UPDATE', user.id);

    // 3. 물리 테이블 동기화
    if (report.tableName) {
        const oldRowData = JSON.parse(row.data);
        const idCol = columns.find((c: any) => c.isAutoGenerated);
        const filterKey = idCol?.name || columns[0].name;
        await DbSyncService.syncToPhysicalTable(report.tableName, newData, columns, { [filterKey]: String(oldRowData[filterKey]) });
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

/**
 * 데이터를 일괄 수정합니다. (Overwrite 또는 Find & Replace)
 */
export async function bulkUpdateRowsAction(
    reportId: string, 
    selectedIds: string[], 
    selectedField: string, 
    mode: 'OVERWRITE' | 'FIND_REPLACE', 
    config: { value?: any; find?: string; replace?: string }
) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await getMasterRecords(String(reportId));
    const report = reports[0];
    const columns = JSON.parse(report.columns);
    
    let successCount = 0;
    const now = new Date().toISOString();

    for (const rowId of selectedIds) {
        try {
            const rows = await queryTable('dashboard_data', { filters: { id: String(rowId) } });
            const row = rows[0];
            if (!row) continue;

            if (user.role === 'VIEWER' && row.creatorId !== user.id) continue;

            let rowData = JSON.parse(row.data);
            const oldValue = rowData[selectedField];
            let newValue = config.value;

            if (mode === 'FIND_REPLACE') {
                const currentStr = String(oldValue || '');
                newValue = currentStr.replace(new RegExp(config.find || '', 'g'), config.replace || '');
            }

            // 데이터 업데이트
            rowData[selectedField] = newValue;
            rowData.__updated_at = now;
            rowData.__modifier_id = user.id;

            const updatedDataStr = JSON.stringify(rowData);

            // 1. 가상 테이블 업데이트
            const updateRes = await updateRows('dashboard_data', {
                data: updatedDataStr,
                updatedAt: now,
                updaterId: user.id
            }, { filters: { id: String(rowId) } });

            if (updateRes && typeof updateRes === 'object' && updateRes.success === false) {
                console.error(`[bulkUpdateRowsAction] Failed to update virtual row ${rowId}:`, updateRes.error);
                continue;
            }

            // 2. 이력 기록
            await HistoryService.recordHistory(rowId, row.data, updatedDataStr, 'BULK_UPDATE', user.id);

            // 3. 물리 테이블 동기화
            if (report.tableName) {
                const idCol = columns.find((c: any) => c.isAutoGenerated);
                const filterKey = idCol?.name || columns[0].name;
                await DbSyncService.syncToPhysicalTable(report.tableName, rowData, columns, { [filterKey]: String(rowData[filterKey]) });
            }
            successCount++;
        } catch (err) {
            console.error(`Failed to bulk update row ${rowId}:`, err);
        }
    }

    logActivity({
        userId: user.id,
        title: `[${report.name}] 데이터 일괄 수정`,
        message: `${successCount}건의 데이터를 [${selectedField}] 기준으로 일괄 수정했습니다.`,
        link: `/report/${reportId}`,
        type: 'ACTIVITY'
    }).catch(console.error);

    revalidatePath(`/report/${reportId}`);
    return { success: true, count: successCount };
}

/**
 * 특정 행의 변경 이력을 조회합니다.
 */
export async function getRowHistoryAction(rowId: string) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    // 1. 기본 데이터 조회 (작성자 정보 포함)
    const [row] = await queryTable('dashboard_data', { filters: { id: String(rowId) } });
    if (!row) throw new Error('데이터를 찾을 수 없습니다.');

    const [creator] = await queryTable('user', { filters: { id: String(row.creatorId) } });
    const [updater] = await queryTable('user', { filters: { id: String(row.updaterId || row.creatorId) } });

    // 2. 이력 조회
    const histories = await queryTable('dashboard_data_history', { 
        filters: { rowId: String(rowId) },
        orderBy: 'changedAt',
        limit: 100
    });

    // 3. 각 이력 항목에 사용자 정보 매핑
    const mappedHistories = [];
    for (const h of histories) {
        const [changedBy] = await queryTable('user', { filters: { id: String(h.changedById) } });
        mappedHistories.push({
            ...h,
            changedBy: changedBy ? {
                id: changedBy.id,
                username: changedBy.username,
                fullName: changedBy.fullName
            } : null
        });
    }

    // 최신순 정렬
    mappedHistories.sort((a, b) => new Date(b.changedAt).getTime() - new Date(a.changedAt).getTime());

    return {
        id: rowId,
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
        creator: creator ? { id: creator.id, username: creator.username, fullName: creator.fullName } : null,
        updater: updater ? { id: updater.id, username: updater.username, fullName: updater.fullName } : null,
        histories: mappedHistories
    };
}

/**
 * 데이터를 삭제합니다. (Soft Delete)
 */
export async function deleteRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const reports = await getMasterRecords(String(reportId));
    const report = reports[0];

    const timestamp = new Date().toISOString();

    const uiConfig = report.uiConfig ? JSON.parse(report.uiConfig) : {};
    if (uiConfig.isIntegrityProtected) {
        throw new Error('데이터 무결성 보호가 설정된 테이블입니다. 삭제하려면 [TABLE CONFIG]에서 보호 설정을 해제해 주세요.');
    }

    let deletedCount = 0;
    for (const id of rowIds) {
        const [row] = await queryTable('dashboard_data', { filters: { id: String(id) } });
        if (!row) continue;
        
        if (user.role === 'VIEWER' && row.creatorId !== user.id) {
            continue;
        }

    // 1. 가상 테이블 논리 삭제
    const updateRes = await updateRows('dashboard_data', {
        __is_deleted: 1,
        contentHash: null,
        __deleted_at: timestamp,
        updaterId: user.id
    }, { filters: { id: String(id) } });

    // [DIAGNOSTIC] Check if update failed
    if (updateRes && typeof updateRes === 'object' && updateRes.success === false) {
        console.error(`[deleteRowsAction] Failed to soft-delete virtual row ${id}:`, updateRes.error);
        continue;
    }

        // 2. 이력 기록
        const rowData = JSON.parse(row.data);
        await HistoryService.recordHistory(id, row.data, { ...rowData, _deleted: true }, 'DELETE', user.id);

        // 3. 물리 테이블 논리 삭제
        if (report.tableName) {
            const columns = JSON.parse(report.columns);
            const idCol = columns.find((c: any) => c.isAutoGenerated);
            const filterKey = idCol?.name || columns[0].name;
            await DbSyncService.deleteFromPhysicalTable(report.tableName, { [filterKey]: String(rowData[filterKey]) }, user.id);
        }
        deletedCount++;
    }

    if (deletedCount === 0 && rowIds.length > 0) {
        throw new Error('삭제할 수 있는 권한이 없거나 대상 데이터를 찾을 수 없습니다.');
    }

    logActivity({
        userId: user.id,
        title: `[${report.name}] 데이터 삭제`,
        message: `${rowIds.length}건의 데이터를 삭제했습니다.`,
        link: `/report/${reportId}`,
        type: 'ACTIVITY'
    }).catch(console.error);

    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

/**
 * 삭제된 데이터를 복구합니다.
 */
export async function restoreRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const reports = await getMasterRecords(String(reportId));
    const report = reports[0];
    const columns = JSON.parse(report.columns);

    let successCount = 0;
    const timestamp = new Date().toISOString();

    for (const id of rowIds) {
        const [row] = await queryTable('dashboard_data', { filters: { id: String(id) } });
        if (!row) continue;

        const rowData = JSON.parse(row.data);
        const hash = await RowService.generateContentHash(rowData, columns);

        // 중복 체크 (이미 활성 상태인 동일 데이터가 있는지)
        const [existing] = await queryTable('dashboard_data', { 
            filters: { reportId, contentHash: hash, __is_deleted: '0' } 
        });
        if (existing) continue;

        // 1. 가상 테이블 복구
        const updateRes = await updateRows('dashboard_data', {
            __is_deleted: 0,
            contentHash: hash,
            __deleted_at: null,
            updatedAt: timestamp,
            updaterId: user.id
        }, { filters: { id: String(id) } });

        if (updateRes && typeof updateRes === 'object' && updateRes.success === false) {
            console.error(`[restoreRowsAction] Failed to restore virtual row ${id}:`, updateRes.error);
            continue;
        }

        // 2. 이력 기록
        await HistoryService.recordHistory(id, row.data, row.data, 'RESTORE', user.id);

        // 3. 물리 테이블 복구
        if (report.tableName) {
            const idCol = columns.find((c: any) => c.isAutoGenerated);
            const filterKey = idCol?.name || columns[0].name;
            await DbSyncService.syncToPhysicalTable(report.tableName, { 
                ...rowData, 
                __is_deleted: 0, 
                __deleted_at: null,
                __modifier_id: user.id
            }, columns, { [filterKey]: String(rowData[filterKey]) });
        }
        successCount++;
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, restoredCount: successCount };
}

/**
 * 가상 테이블과 물리 테이블의 데이터 정합성을 확인합니다.
 */
export async function checkSyncStatusAction(reportId: string) {
    try {
        const reports = await getMasterRecords(String(reportId));
        const report = reports[0];
        if (!report || !report.tableName) return { status: 'no-physical' };

        const virtualResult: any = await queryTable('dashboard_data', { 
            filters: { reportId: String(reportId), __is_deleted: '0' } 
        });
        const virtualCount = Array.isArray(virtualResult) ? virtualResult.length : (virtualResult?.rows?.length || 0);

        const physicalResult: any = await queryTable(report.tableName, { 
            filters: { __is_deleted: '0' },
            limit: 100000 
        });
        const physicalCount = Array.isArray(physicalResult) ? physicalResult.length : (physicalResult?.rows?.length || 0);

        if (virtualCount === physicalCount) {
            return { status: 'synced', virtualCount, physicalCount, diff: 0 };
        } else {
            return { 
                status: 'mismatch', 
                virtualCount, 
                physicalCount, 
                diff: Math.abs(virtualCount - physicalCount),
                message: `데이터 개수가 일치하지 않습니다. (가상: ${virtualCount}, 물리: ${physicalCount})`
            };
        }
    } catch (err: any) {
        return { status: 'error', message: err.message || '상태 확인 실패' };
    }
}
