'use server';

import { revalidatePath } from 'next/cache';
import { 
    queryTable, 
    insertRows, 
    updateRows, 
    deleteRows
} from '@/egdesk-helpers';
import { 
    checkReportAuthorization
} from './shared';
import { getSessionAction } from './auth';
import { notifyNewDataRow, notifyBulkUpload, logActivity } from '@/lib/notifications';
import { triggerWorkflow } from '@/lib/workflow/engine';
import { ValidationService } from '@/lib/services/validation-service';
import { HistoryService } from '@/lib/services/history-service';
import { DbSyncService } from '@/lib/services/db-sync-service';
import { RowService } from '@/lib/services/row-service';

/**
 * 보고서에 새로운 데이터를 추가합니다.
 */
export async function addRowAction(reportId: string, rowData: any) {
  const user = await getSessionAction();
  if (!user) throw new Error('인증이 필요합니다.');
  
  const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
  if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

  const reports: any = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
  const report = reports[0];
  if (!report) throw new Error('보고서를 찾을 수 없습니다.');

  const columns = JSON.parse(report.columns);
  
  // 1. 유효성 검사 및 데이터 정제
  const { isValid, error, cleanedData } = ValidationService.validateRowData(rowData, columns);
  if (!isValid) throw new Error(error);

  let syncWarning: string | null = null;
  const hash = await RowService.generateContentHash(cleanedData, columns);

  // 2. 중복 체크
  try {
      const existingRows: any = await queryTable('dashboard_data', {
          filters: { reportId: String(reportId), contentHash: String(hash), isDeleted: '0' }
      });
      if (existingRows.length > 0) throw new Error('이미 동일한 내용의 데이터가 존재합니다. (중복 방지)');
  } catch (err: any) {
      if (err.message.includes('중복 방지')) throw err;
      // 컬럼이 없거나 쿼리 오류 발생 시 로그를 남기고 진행합니다.
      console.warn(`중복 체크 스킵 (스키마 누락 등): ${err.message}`);
  }

  // 3. 자동 ID 생성 (DID-000001 등)
  const idCol = columns.find((c: any) => c.isAutoGenerated);
  if (idCol) {
      const nextSerial = await RowService.calculateNextSerial(reportId, report.tableName, idCol.name);
      cleanedData[idCol.name] = `${idCol.autoPrefix || 'DID-'}${nextSerial.toString().padStart(6, '0')}`;
      
      // 일련번호 업데이트 (실패해도 진행)
      updateRows('dashboard_master', { lastSerial: nextSerial }, { filters: { reportId: String(reportId) } }).catch(() => {});
  }

  // 4. 저장 (물리 + 가상 테이블)
  const saveResult: any = await RowService.saveRow(reportId, report.tableName, columns, cleanedData, hash, user.id);
  if (saveResult?.syncError) {
      syncWarning = saveResult.syncError;
  }

  const firstCol = columns.find((c: any) => !c.isAutoGenerated) || columns[0];
  const summary = firstCol ? cleanedData[firstCol.name] : 'N/A';

  logActivity({
      userId: user.id,
      title: `[${report.name}] 데이터 등록`,
      message: `[${summary}] 항목을 새롭게 등록했습니다.`,
      link: `/report/${reportId}`,
      type: 'ACTIVITY'
  }).catch(console.error);
  triggerWorkflow(reportId, cleanedData, user.id).catch(console.error);

  revalidatePath(`/report/${reportId}`);
  return { success: true, syncWarning };
}

/**
 * 대량의 데이터를 한꺼번에 추가합니다. (예: 엑셀 업로드)
 */
export async function addRowsAction(reportId: string, rows: any[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
    const report = reports[0];
    if (!report) throw new Error('보고서를 찾을 수 없습니다.');
  
    const columns = JSON.parse(report.columns);
    const idCol = columns.find((c: any) => c.isAutoGenerated);
    let nextSerial = await RowService.calculateNextSerial(reportId, report.tableName, idCol?.name);

    const cleanedRowsToInsert = [];
    let skippedCount = 0;
    
    // 기존 해시값 로드 (중복 방지용)
    const existingRows = await queryTable('dashboard_data', { filters: { reportId: String(reportId), isDeleted: '0' } });
    const existingHashes = new Set(existingRows.map((r: any) => r.contentHash));

    for (const rowData of rows) {
        const { isValid, cleanedData } = ValidationService.validateRowData(rowData, columns);
        if (!isValid) { skippedCount++; continue; }

        const hash = await RowService.generateContentHash(cleanedData, columns);
        if (existingHashes.has(hash)) { skippedCount++; continue; }

        if (idCol) {
            cleanedData[idCol.name] = `${idCol.autoPrefix || 'DID-'}${nextSerial.toString().padStart(6, '0')}`;
            nextSerial++;
        }

        cleanedRowsToInsert.push({
            reportId: String(reportId),
            data: cleanedData,
            contentHash: hash
        });
        existingHashes.add(hash);
    }

    if (cleanedRowsToInsert.length > 0) {
        // 물리 테이블 일괄 삽입
        if (report.tableName) {
            await DbSyncService.insertToPhysicalTable(report.tableName, cleanedRowsToInsert.map(r => r.data), columns);
        }

        // 가상 테이블 일괄 삽입
        const virtualRows = cleanedRowsToInsert.map(r => ({
            id: Math.floor(Math.random() * 2147483647),
            reportId: r.reportId,
            data: JSON.stringify(r.data),
            contentHash: r.contentHash,
            creatorId: user.id,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            isDeleted: 0
        }));
        await insertRows('dashboard_data', virtualRows);
        
        // 마지막 일련번호 업데이트
        if (idCol) {
            await updateRows('dashboard_master', { lastSerial: nextSerial - 1 }, { filters: { reportId: String(reportId) } });
        }
    }
  
    notifyBulkUpload(report.name, user.fullName || user.username, cleanedRowsToInsert.length, cleanedRowsToInsert[0]?.data, columns, report.slackWebhookUrl).catch(console.error);
    logActivity({
        userId: user.id,
        title: `[${report.name}] 대량 업로드`,
        message: `${cleanedRowsToInsert.length}건의 데이터를 일괄 등록했습니다.`,
        link: `/report/${reportId}`,
        type: 'ACTIVITY'
    }).catch(console.error);

    revalidatePath('/report/' + reportId);
    return { success: true, addedCount: cleanedRowsToInsert.length, skippedCount };
}

/**
 * 단일 행 데이터를 수정합니다.
 */
export async function updateSingleRowAction(reportId: string, rowId: string, newData: any) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const isAuthorized = await checkReportAuthorization(reportId, user.id, user.role);
    if (!isAuthorized) throw new Error('해당 보고서에 대한 접근 권한이 없습니다.');

    const reports = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
    const report = reports[0];
    const columns = JSON.parse(report.columns);
    const rows = await queryTable('dashboard_data', { filters: { id: String(rowId) } });
    const row = rows[0];

    if (user.role === 'VIEWER' && row.creatorId !== user.id) {
        throw new Error('본인이 작성하지 않은 데이터는 수정할 수 없습니다.');
    }

    // 1. 가상 테이블 업데이트
    const updatedDataStr = JSON.stringify(newData);
    await updateRows('dashboard_data', {
        data: updatedDataStr,
        updatedAt: new Date().toISOString(),
        updaterId: user.id
    }, { filters: { id: String(rowId) } });

    // 2. 이력 기록
    await HistoryService.recordHistory(rowId, row.data, updatedDataStr, 'UPDATE', user.id);

    // 3. 물리 테이블 동기화
    if (report.tableName) {
        const oldRowData = JSON.parse(row.data);
        const idCol = columns.find((c: any) => c.isAutoGenerated);
        const filterKey = idCol?.name || columns[0].name;
        await DbSyncService.syncToPhysicalTable(report.tableName, newData, columns, { [filterKey]: String(oldRowData[filterKey]) });
    }

    logActivity({
        userId: user.id,
        title: `[${report.name}] 데이터 수정`,
        message: `데이터 내용을 수정했습니다.`,
        link: `/report/${reportId}`,
        type: 'ACTIVITY'
    }).catch(console.error);

    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

/**
 * 여러 행의 데이터를 일괄 수정합니다.
 */
export async function bulkUpdateRowsAction(reportId: string, rowIds: string[], fieldName: string, actionType: 'OVERWRITE' | 'FIND_REPLACE', params: { value?: any; find?: string; replace?: string }) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');
    
    const reports = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
    const report = reports[0];
    const columns = JSON.parse(report.columns);
    const colDef = columns.find((c: any) => c.name === fieldName);

    for (const id of rowIds) {
        const [row] = await queryTable('dashboard_data', { filters: { id: String(id) } });
        if (!row || (user.role === 'VIEWER' && row.creatorId !== user.id)) continue;

        const rowData = JSON.parse(row.data);
        let newValue = params.value;

        if (actionType === 'FIND_REPLACE' && params.find !== undefined && params.replace !== undefined) {
            newValue = String(rowData[fieldName] || '').replace(new RegExp(params.find, 'g'), params.replace);
        }

        // 타입 검증 (숫자형)
        if ((colDef.type === 'number' || colDef.type === 'currency') && newValue) {
            newValue = Number(String(newValue).replace(/[^0-9.-]/g, ''));
        }

        rowData[fieldName] = newValue;
        const newHash = await RowService.generateContentHash(rowData, columns);

        await updateRows('dashboard_data', {
            data: JSON.stringify(rowData),
            contentHash: newHash,
            updaterId: user.id,
            updatedAt: new Date().toISOString()
        }, { filters: { id: String(id) } });

        await HistoryService.recordHistory(id, row.data, rowData, 'UPDATE', user.id);

        if (report.tableName) {
            const idCol = columns.find((c: any) => c.isAutoGenerated);
            const filterKey = idCol?.name || columns[0].name;
            await DbSyncService.syncToPhysicalTable(report.tableName, rowData, columns, { [filterKey]: String(JSON.parse(row.data)[filterKey]) });
        }
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, count: rowIds.length };
}

/**
 * 데이터를 삭제합니다. (Soft Delete)
 */
export async function deleteRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const reports = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
    const report = reports[0];

    for (const id of rowIds) {
        const [row] = await queryTable('dashboard_data', { filters: { id: String(id) } });
        if (!row || (user.role === 'VIEWER' && row.creatorId !== user.id)) continue;

        await updateRows('dashboard_data', {
            isDeleted: 1,
            contentHash: null,
            deletedAt: new Date().toISOString(),
            updaterId: user.id
        }, { filters: { id: String(id) } });

        await HistoryService.recordHistory(id, row.data, { ...JSON.parse(row.data), _deleted: true }, 'DELETE', user.id);

        if (report.tableName) {
            const rowData = JSON.parse(row.data);
            const columns = JSON.parse(report.columns);
            const idCol = columns.find((c: any) => c.isAutoGenerated);
            const filterKey = idCol?.name || columns[0].name;
            await DbSyncService.deleteFromPhysicalTable(report.tableName, { [filterKey]: String(rowData[filterKey]) });
        }
    }

    logActivity({
        userId: user.id,
        title: `[${report.name}] 데이터 삭제`,
        message: `${rowIds.length}건의 데이터를 삭제했습니다.`,
        link: `/report/${reportId}`,
        type: 'ACTIVITY'
    }).catch(console.error);

    revalidatePath(`/report/${reportId}`);
    return { success: true };
}

/**
 * 삭제된 데이터를 복구합니다.
 */
export async function restoreRowsAction(reportId: string, rowIds: string[]) {
    const user = await getSessionAction();
    if (!user) throw new Error('인증이 필요합니다.');

    const reports = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
    const report = reports[0];
    const columns = JSON.parse(report.columns);

    let successCount = 0;
    for (const id of rowIds) {
        const [row] = await queryTable('dashboard_data', { filters: { id: String(id) } });
        if (!row) continue;

        const rowData = JSON.parse(row.data);
        const hash = await RowService.generateContentHash(rowData, columns);

        // 중복 체크 (이미 활성 상태인 동일 데이터가 있는지)
        const [existing] = await queryTable('dashboard_data', { filters: { reportId, contentHash: hash, isDeleted: '0' } });
        if (existing) continue;

        await updateRows('dashboard_data', {
            isDeleted: 0,
            contentHash: hash,
            deletedAt: null,
            updatedAt: new Date().toISOString(),
            updaterId: user.id
        }, { filters: { id: String(id) } });

        await HistoryService.recordHistory(id, row.data, row.data, 'RESTORE', user.id);

        if (report.tableName) {
            await DbSyncService.insertToPhysicalTable(report.tableName, [rowData], columns);
        }
        successCount++;
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, restoredCount: successCount };
}

/**
 * 데이터의 변경 이력을 조회합니다.
 */
export async function getRowHistoryAction(rowId: string) {
    const [row] = await queryTable('dashboard_data', { filters: { id: String(rowId) } });
    if (!row) throw new Error('데이터를 찾을 수 없습니다.');

    let histories: any[] = [];
    try {
        histories = await queryTable('dashboard_data_history', { 
            filters: { rowId: String(rowId) },
            orderBy: 'changedAt',
            orderDirection: 'DESC'
        });
    } catch (e) {}

    const distinctUserIds = Array.from(new Set(histories.map((h: any) => h.changedById).filter(id => !!id)));
    const userMap: Record<string, any> = {};
    for (const uid of distinctUserIds) {
        const [u] = await queryTable('user', { filters: { id: String(uid) } });
        if (u) userMap[uid] = u;
    }

    return {
        id: row.id,
        data: row.data,
        createdAt: row.createdAt,
        histories: histories.map(h => ({
            ...h,
            changedBy: userMap[h.changedById] || (h.changedById === 'system' ? { fullName: '시스템' } : null)
        }))
    };
}

/**
 * 가상 테이블과 물리 테이블의 데이터 정합성을 확인합니다.
 */
export async function checkSyncStatusAction(reportId: string) {
    try {
        const reports = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
        const report = reports[0];
        if (!report || !report.tableName) return { status: 'no-physical' };

        const virtualResult: any = await queryTable('dashboard_data', { filters: { reportId: String(reportId), isDeleted: '0' } });
        const virtualCount = Array.isArray(virtualResult) ? virtualResult.length : (virtualResult?.rows?.length || 0);

        const physicalResult: any = await queryTable(report.tableName, { limit: 100000 });
        const physicalCount = Array.isArray(physicalResult) ? physicalResult.length : (physicalResult?.rows?.length || 0);

        if (virtualCount === physicalCount) {
            return { status: 'synced', virtualCount, physicalCount, diff: 0 };
        } else {
            return { 
                status: 'mismatch', 
                virtualCount, 
                physicalCount, 
                diff: Math.abs(virtualCount - physicalCount),
                message: `데이터 개수가 일치하지 않습니다. (가상: ${virtualCount}, 물리: ${physicalCount})`
            };
        }
    } catch (err: any) {
        return { status: 'error', message: err.message || '상태 확인 실패' };
    }
}

/**
 * 물리 테이블을 기준으로 가상 테이블 데이터를 강제 동기화합니다.
 */
export async function repairVirtualTableAction(reportId: string) {
    const user = await getSessionAction();
    if (!user || user.role !== 'ADMIN') throw new Error('관리자 권한이 필요합니다.');

    const reports = await queryTable('dashboard_master', { filters: { reportId: String(reportId) } });
    const report = reports[0];
    if (!report || !report.tableName) throw new Error('물리 테이블 정보가 없습니다.');

    // 1. 가상 데이터 모두 삭제
    await deleteRows('dashboard_data', { filters: { reportId: String(reportId) } });

    // 2. 물리 데이터 로드
    const physicalRows: any = await queryTable(report.tableName, { limit: 100000 });
    const rowsArray = Array.isArray(physicalRows) ? physicalRows : (physicalRows?.rows || []);
    const columns = JSON.parse(report.columns);

    // 3. 가상 데이터로 다시 삽입
    if (rowsArray.length > 0) {
        const virtualRows = await Promise.all(rowsArray.map(async (pRow: any) => {
            const hash = await RowService.generateContentHash(pRow, columns);
            return {
                id: Math.floor(Math.random() * 2147483647),
                reportId: String(reportId),
                data: JSON.stringify(pRow),
                contentHash: hash,
                creatorId: 'system-repair',
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
                isDeleted: 0
            };
        }));
        
        // 500개씩 끊어서 벌크 인서트 (SQLite 제약 고려)
        for (let i = 0; i < virtualRows.length; i += 500) {
            await insertRows('dashboard_data', virtualRows.slice(i, i + 500));
        }
    }

    revalidatePath(`/report/${reportId}`);
    return { success: true, message: `${rowsArray.length}개의 데이터를 물리 테이블 기준으로 복구했습니다.` };
}
